#!/usr/bin/env python3
"""
Germline_SNP_Enrichment_Analysis.py
====================================
Germline SNP enrichment between HIGH-SBS2 and LOW-SBS2 HNSCC tumors.

Hypothesis: Patient-specific germline variants may modulate A3 enzymatic
activity, explaining why some tumors with similar A3 expression accumulate
high SBS2 while others do not.

Strategy:
  - Tier 1 germline variants: SNPs flagged with alt_allele_in_normal
    (variant detected in patient's matched normal sample)
  - Group selection: identical to network pipeline Step03
    (A3 median filter, rank by SBS2, equal-sized top/bottom 25%)
  - Per-variant Fisher's exact test (HIGH vs LOW)
  - BH correction, gene-level aggregation
  - Chromosome ideogram visualization
  - KEGG pathway enrichment

Inputs:
  - consolidated/per_cancer/TCGA-HNSC_mutations.maf.tsv
  - data/FIG_1/HNSC_A3_SBS2_matched_v3.tsv

Outputs (-> data/FIG_GERMLINE/):
  - germline_snp_enrichment_results.tsv
  - germline_gene_level_results.tsv
  - Germline_Chromosome_Ideogram.pdf/.png
  - germline_enrichment_report.txt

Author: Jake Lehle / Claude (2026 NMF Paper)
"""

import os, sys, time
import numpy as np
import pandas as pd
import matplotlib; matplotlib.use('Agg')
import matplotlib.pyplot as plt
import matplotlib.patches as mpatches
from matplotlib.collections import LineCollection
from scipy.stats import fisher_exact
from statsmodels.stats.multitest import multipletests

# =============================================================================
# CONFIGURATION
# =============================================================================
PROJECT_ROOT = "/master/jlehle/WORKING/2026_NMF_PAPER"
BASE_VCF = "/master/jlehle/SHARED/TCGA/VCF"

MAF_PATH = os.path.join(BASE_VCF, "consolidated", "per_cancer", "TCGA-HNSC_mutations.maf.tsv")
MATCHED_PATH = os.path.join(PROJECT_ROOT, "data", "FIG_1", "HNSC_A3_SBS2_matched_v3.tsv")

# A3 interactors (generated by Extract_Harris_A3_Interactors.py)
HARRIS_ALL_PATH = os.path.join(PROJECT_ROOT, "data", "FIG_4", "00_input", "Harris_A3_interactors.txt")
HARRIS_A3B_PATH = os.path.join(PROJECT_ROOT, "data", "FIG_4", "00_input", "Harris_A3_interactors_A3B_only.txt")

OUTPUT_DIR = os.path.join(PROJECT_ROOT, "data", "FIG_GERMLINE")
PANEL_DIR = os.path.join(OUTPUT_DIR, "PANELS")
TROUBLE_DIR = os.path.join(OUTPUT_DIR, "TROUBLESHOOTING")
for d in [OUTPUT_DIR, PANEL_DIR, TROUBLE_DIR]:
    os.makedirs(d, exist_ok=True)

# Group selection parameters (MUST MATCH network_config.py / Step03)
A3_SUM_PERCENTILE = 0.50      # median
SBS2_GROUP_FRACTION = 0.25    # top/bottom 25% of high-A3 tumors

# Germline filter
GERMLINE_FLAG = 'alt_allele_in_normal'  # Tier 1: patient's normal carries variant

# Recurrence filter
# With n=53 per group, Fisher's exact requires at least 5 carriers all in
# one group to reach p < 0.05 (4/0 split gives p ~ 0.057, 5/0 gives p ~ 0.028).
# Setting MIN_RECURRENCE = 5 ensures every tested variant has at least
# theoretical power to reach significance, reducing the multiple testing
# burden from thousands of untestable singletons.
MIN_RECURRENCE = 5

# Significance thresholds (report all three, primary is 0.05)
BH_STRICT = 0.05       # standard FDR threshold
BH_MODERATE = 0.10     # exploratory threshold
BH_SUGGESTIVE = 0.25   # hypothesis-generating tier

# Figure style
FONT_SIZE = 30
COLOR_SBS2_HIGH = "#ed6a5a"
COLOR_CREAM = "#f4f1bb"
COLOR_NORMAL = "#9bc1bc"
COLOR_DARK_GRAY = "#4D4D4D"
COLOR_BLACK = "#000000"
COLOR_SIG = "#bf616a"         # significant hits
COLOR_NONSIG = "#b0b0b0"     # non-significant

plt.rcParams.update({
    'font.size': FONT_SIZE,
    'axes.titlesize': FONT_SIZE,
    'axes.labelsize': FONT_SIZE,
    'xtick.labelsize': FONT_SIZE - 6,
    'ytick.labelsize': FONT_SIZE - 6,
    'legend.fontsize': FONT_SIZE - 8,
    'font.family': 'sans-serif',
    'font.sans-serif': ['Arial', 'DejaVu Sans'],
})

# =============================================================================
# LOGGING
# =============================================================================
report_lines = []
def log(msg=""):
    print(msg, flush=True); report_lines.append(str(msg))
def banner(title, char="="):
    log(""); log(char * 80); log(f"  {title}"); log(char * 80)

def save_fig(fig, name, panel_dir=PANEL_DIR):
    for ext in ['pdf', 'png']:
        fig.savefig(os.path.join(panel_dir, f"{name}.{ext}"), dpi=300, bbox_inches='tight')
    plt.close(fig); log(f"  Saved: {name}.pdf/.png")

pipeline_start = time.time()

# =============================================================================
# STEP 1: LOAD DATA
# =============================================================================
banner("STEP 1: Load Data")

# Load matched table (426 DIRECT-only tumors)
v3 = pd.read_csv(MATCHED_PATH, sep='\t')
log(f"  v3 matched table: {len(v3)} tumors")

# Load HNSC MAF
log(f"  Reading MAF: {MAF_PATH}")
maf_cols = ['Hugo_Symbol', 'Chromosome', 'Start_Position', 'End_Position',
            'Reference_Allele', 'Tumor_Seq_Allele2', 'Variant_Type',
            'Variant_Classification', 'FILTER', 'Tumor_Sample_Barcode',
            'dbSNP_RS', 'IMPACT', 'Consequence',
            'n_depth', 'n_ref_count', 'n_alt_count']
maf = pd.read_csv(MAF_PATH, sep='\t', usecols=maf_cols, low_memory=False)
log(f"  MAF rows: {len(maf):,}")

# =============================================================================
# STEP 2: SELECT EQUAL-SIZED HIGH vs LOW GROUPS
# (identical logic to network Step03)
# =============================================================================
banner("STEP 2: Select HIGH vs LOW Groups (Step03 logic)")

# 1. A3 median filter
a3_median = v3['A3A_plus_A3B'].median()
high_a3 = v3[v3['A3A_plus_A3B'] >= a3_median].copy()
log(f"  A3A+A3B median: {a3_median:.2f}")
log(f"  Tumors above A3 median: {len(high_a3)}")

# 2. Rank by SBS2, take equal-sized top/bottom 25%
high_a3_ranked = high_a3.sort_values('SBS2', ascending=True).reset_index(drop=True)
n_high_a3 = len(high_a3_ranked)
n_per_group = int(np.floor(n_high_a3 * SBS2_GROUP_FRACTION))

group_low = high_a3_ranked.iloc[:n_per_group].copy()
group_high = high_a3_ranked.iloc[-n_per_group:].copy()

sbs2_low_max = group_low['SBS2'].max()
sbs2_high_min = group_high['SBS2'].min()

high_patients = set(group_high['WES_Barcode'].str[:12].values)
low_patients = set(group_low['WES_Barcode'].str[:12].values)

log(f"  High-A3 tumors: {n_high_a3}")
log(f"  Tumors per group (floor 25%): {n_per_group}")
log(f"  HIGH group: n={len(high_patients)}, SBS2 range: {sbs2_high_min:.0f} - {group_high['SBS2'].max():.0f}")
log(f"  LOW group:  n={len(low_patients)}, SBS2 range: {group_low['SBS2'].min():.0f} - {sbs2_low_max:.0f}")
log(f"  A3A+A3B mean HIGH: {group_high['A3A_plus_A3B'].mean():.2f}")
log(f"  A3A+A3B mean LOW:  {group_low['A3A_plus_A3B'].mean():.2f}")

assert len(high_patients) == len(low_patients), \
    f"Groups not equal! HIGH={len(high_patients)}, LOW={len(low_patients)}"
log(f"  CONFIRMED: equal group sizes ({n_per_group} each)")

# =============================================================================
# STEP 3: EXTRACT TIER 1 GERMLINE SNPs
# =============================================================================
banner("STEP 3: Extract Tier 1 Germline SNPs")

# Add patient ID
maf['patient_id'] = maf['Tumor_Sample_Barcode'].str[:12]

# Filter to: SNPs with alt_allele_in_normal flag, in our patient set
all_patients = high_patients | low_patients
maf_our = maf[maf['patient_id'].isin(all_patients)].copy()
log(f"  MAF rows for {len(all_patients)} patients: {len(maf_our):,}")

# Filter to SNPs with germline flag
germline_mask = (
    (maf_our['Variant_Type'] == 'SNP') &
    (maf_our['FILTER'].str.contains(GERMLINE_FLAG, case=False, na=False))
)
germline = maf_our[germline_mask].copy()
log(f"  Tier 1 germline SNPs (alt_allele_in_normal): {len(germline):,}")
log(f"  Patients with germline SNPs: {germline['patient_id'].nunique()}")

# Create variant ID
germline['variant_id'] = (germline['Chromosome'] + ':' +
                           germline['Start_Position'].astype(str) + ':' +
                           germline['Reference_Allele'] + '>' +
                           germline['Tumor_Seq_Allele2'])

# Per-patient counts
per_patient = germline.groupby('patient_id').size()
log(f"\n  Germline SNPs per patient:")
log(f"    Mean:   {per_patient.mean():.0f}")
log(f"    Median: {per_patient.median():.0f}")

# =============================================================================
# STEP 4: BUILD PATIENT x VARIANT MATRIX AND APPLY RECURRENCE FILTER
# =============================================================================
banner("STEP 4: Recurrence Filter")

# For each variant, which patients carry it?
variant_patients = germline.groupby('variant_id')['patient_id'].apply(set).to_dict()
variant_n_patients = {v: len(p) for v, p in variant_patients.items()}

total_variants = len(variant_patients)
recurrent_variants = {v: p for v, p in variant_patients.items()
                      if len(p) >= MIN_RECURRENCE}

log(f"  Total unique germline variants: {total_variants:,}")
log(f"  Variants in >= {MIN_RECURRENCE} patients: {len(recurrent_variants):,}")

# Also get gene annotations for recurrent variants
variant_gene = germline.groupby('variant_id')['Hugo_Symbol'].first().to_dict()
variant_chrom = germline.groupby('variant_id')['Chromosome'].first().to_dict()
variant_pos = germline.groupby('variant_id')['Start_Position'].first().to_dict()
variant_class = germline.groupby('variant_id')['Variant_Classification'].first().to_dict()
variant_impact = germline.groupby('variant_id')['IMPACT'].first().to_dict()
variant_dbsnp = germline.groupby('variant_id')['dbSNP_RS'].first().to_dict()

# =============================================================================
# STEP 5: FISHER'S EXACT TEST PER VARIANT
# =============================================================================
banner("STEP 5: Fisher's Exact Test")

n_high = len(high_patients)
n_low = len(low_patients)

results = []
for vid, carriers in recurrent_variants.items():
    high_carriers = carriers & high_patients
    low_carriers = carriers & low_patients

    a = len(high_carriers)      # HIGH + variant
    b = n_high - a              # HIGH + no variant
    c = len(low_carriers)       # LOW + variant
    d = n_low - c               # LOW + no variant

    table = [[a, b], [c, d]]
    odds_ratio, pval = fisher_exact(table, alternative='two-sided')

    results.append({
        'variant_id': vid,
        'chromosome': variant_chrom.get(vid, ''),
        'position': variant_pos.get(vid, 0),
        'gene': variant_gene.get(vid, ''),
        'variant_class': variant_class.get(vid, ''),
        'impact': variant_impact.get(vid, ''),
        'dbSNP': variant_dbsnp.get(vid, ''),
        'n_high': a,
        'n_low': c,
        'n_total': a + c,
        'freq_high': a / n_high,
        'freq_low': c / n_low,
        'odds_ratio': odds_ratio,
        'pval': pval,
    })

results_df = pd.DataFrame(results)
log(f"  Tested variants: {len(results_df):,}")

# BH correction
if len(results_df) > 0:
    reject, pval_bh, _, _ = multipletests(results_df['pval'], method='fdr_bh')
    results_df['pval_bh'] = pval_bh
    results_df['sig_strict'] = pval_bh < BH_STRICT
    results_df['sig_moderate'] = pval_bh < BH_MODERATE
    results_df['sig_suggestive'] = pval_bh < BH_SUGGESTIVE
    # Primary significance column (used for ideogram coloring)
    results_df['significant'] = results_df['sig_moderate']
    results_df = results_df.sort_values('pval').reset_index(drop=True)

    log(f"  BH-corrected results ({len(results_df):,} tests):")
    log(f"    BH < {BH_STRICT} (strict):      {results_df['sig_strict'].sum()}")
    log(f"    BH < {BH_MODERATE} (moderate):    {results_df['sig_moderate'].sum()}")
    log(f"    BH < {BH_SUGGESTIVE} (suggestive):  {results_df['sig_suggestive'].sum()}")
    log(f"    Nominal p < 0.05:          {(results_df['pval'] < 0.05).sum()}")
    log(f"    Nominal p < 0.01:          {(results_df['pval'] < 0.01).sum()}")

    # Power analysis note
    log(f"\n  POWER ANALYSIS NOTE:")
    log(f"    With n={n_per_group} per group, detectable effects at p < 0.05:")
    for freq in [0.05, 0.10, 0.15, 0.20, 0.30]:
        n_carriers = int(np.round(freq * (n_high + n_low)))
        # Most extreme split: all in HIGH
        max_high = min(n_carriers, n_high)
        max_low = 0
        if max_high >= 1:
            table_extreme = [[max_high, n_high - max_high], [max_low, n_low - max_low]]
            _, p_extreme = fisher_exact(table_extreme, alternative='two-sided')
            log(f"    Frequency {freq:.0%} ({n_carriers} carriers): "
                f"most extreme split = {max_high}/{max_low}, p = {p_extreme:.4f}")
        else:
            log(f"    Frequency {freq:.0%}: too few carriers")

    # Top hits
    log(f"\n  Top 30 variants by p-value:")
    log(f"  {'Variant':40s} {'Gene':15s} {'HIGH':>5s} {'LOW':>5s} {'OR':>7s} {'p_raw':>10s} {'p_BH':>10s} {'Impact':>10s}")
    log(f"  {'-'*40} {'-'*15} {'-'*5} {'-'*5} {'-'*7} {'-'*10} {'-'*10} {'-'*10}")
    for _, row in results_df.head(30).iterrows():
        sig_mark = '*' if row['significant'] else ''
        log(f"  {row['variant_id']:40s} {row['gene']:15s} {row['n_high']:>5d} {row['n_low']:>5d} "
            f"{row['odds_ratio']:>7.2f} {row['pval']:>10.4f} {row['pval_bh']:>10.4f} {str(row['impact']):>10s} {sig_mark}")

    # Save variant-level results
    results_path = os.path.join(OUTPUT_DIR, "germline_snp_enrichment_results.tsv")
    results_df.to_csv(results_path, sep='\t', index=False)
    log(f"\n  Saved: {results_path}")

# =============================================================================
# STEP 6: GENE-LEVEL AGGREGATION
# =============================================================================
banner("STEP 6: Gene-Level Aggregation")

if len(results_df) > 0:
    # For each gene: count significant variants, best p-value, total variants tested
    gene_stats = results_df.groupby('gene').agg(
        n_variants_tested=('pval', 'count'),
        n_sig_variants=('significant', 'sum'),
        best_pval=('pval', 'min'),
        best_pval_bh=('pval_bh', 'min'),
        mean_odds_ratio=('odds_ratio', 'mean'),
        total_high_carriers=('n_high', 'sum'),
        total_low_carriers=('n_low', 'sum'),
    ).reset_index()

    # Gene-level Fisher's test: does this gene carry ANY germline variant
    # more frequently in HIGH vs LOW?
    gene_fisher_results = []
    for gene in gene_stats['gene'].unique():
        gene_variants = results_df[results_df['gene'] == gene]
        gene_variant_ids = set(gene_variants['variant_id'])

        # Patients carrying ANY variant in this gene
        gene_high_carriers = set()
        gene_low_carriers = set()
        for vid in gene_variant_ids:
            if vid in recurrent_variants:
                gene_high_carriers |= (recurrent_variants[vid] & high_patients)
                gene_low_carriers |= (recurrent_variants[vid] & low_patients)

        a = len(gene_high_carriers)
        b = n_high - a
        c = len(gene_low_carriers)
        d = n_low - c

        if a + c >= MIN_RECURRENCE:
            odds_ratio, pval = fisher_exact([[a, b], [c, d]], alternative='two-sided')
            gene_fisher_results.append({
                'gene': gene,
                'n_high_any': a,
                'n_low_any': c,
                'gene_or': odds_ratio,
                'gene_pval': pval,
            })

    gene_fisher_df = pd.DataFrame(gene_fisher_results)
    if len(gene_fisher_df) > 0:
        _, gene_pval_bh, _, _ = multipletests(gene_fisher_df['gene_pval'], method='fdr_bh')
        gene_fisher_df['gene_pval_bh'] = gene_pval_bh

    # Merge
    gene_results = gene_stats.merge(gene_fisher_df, on='gene', how='left')
    gene_results = gene_results.sort_values('best_pval').reset_index(drop=True)

    log(f"  Genes tested: {len(gene_results)}")
    if 'gene_pval_bh' in gene_results.columns:
        log(f"  Gene-level BH < {BH_STRICT}:  {(gene_results['gene_pval_bh'] < BH_STRICT).sum()}")
        log(f"  Gene-level BH < {BH_MODERATE}: {(gene_results['gene_pval_bh'] < BH_MODERATE).sum()}")
        log(f"  Gene-level BH < {BH_SUGGESTIVE}: {(gene_results['gene_pval_bh'] < BH_SUGGESTIVE).sum()}")
        log(f"  Gene-level nominal p < 0.05: {(gene_results['gene_pval'] < 0.05).sum()}")

    log(f"\n  Top 30 genes by best variant p-value:")
    log(f"  {'Gene':15s} {'nVar':>5s} {'nSig':>5s} {'BestP':>10s} {'GenOR':>7s} {'GeneP':>10s} {'GenBH':>10s}")
    log(f"  {'-'*15} {'-'*5} {'-'*5} {'-'*10} {'-'*7} {'-'*10} {'-'*10}")
    for _, row in gene_results.head(30).iterrows():
        gene_or = row.get('gene_or', np.nan)
        gene_p = row.get('gene_pval', np.nan)
        gene_bh = row.get('gene_pval_bh', np.nan)
        log(f"  {row['gene']:15s} {int(row['n_variants_tested']):>5d} {int(row['n_sig_variants']):>5d} "
            f"{row['best_pval']:>10.4f} {gene_or:>7.2f} {gene_p:>10.4f} {gene_bh:>10.4f}")

    gene_results_path = os.path.join(OUTPUT_DIR, "germline_gene_level_results.tsv")
    gene_results.to_csv(gene_results_path, sep='\t', index=False)
    log(f"\n  Saved: {gene_results_path}")

# =============================================================================
# STEP 7: CHROMOSOME IDEOGRAM
# =============================================================================
banner("STEP 7: Chromosome Ideogram")

if len(results_df) > 0:
    # GRCh38 chromosome sizes (approximate, in Mb)
    chrom_sizes = {
        'chr1': 249, 'chr2': 242, 'chr3': 198, 'chr4': 190, 'chr5': 182,
        'chr6': 171, 'chr7': 159, 'chr8': 145, 'chr9': 138, 'chr10': 134,
        'chr11': 135, 'chr12': 133, 'chr13': 114, 'chr14': 107, 'chr15': 102,
        'chr16': 90, 'chr17': 84, 'chr18': 80, 'chr19': 59, 'chr20': 65,
        'chr21': 47, 'chr22': 51, 'chrX': 156, 'chrY': 57,
    }
    chrom_order = [f'chr{i}' for i in range(1, 23)] + ['chrX', 'chrY']

    # Prepare data
    plot_df = results_df[results_df['chromosome'].isin(chrom_order)].copy()
    plot_df['pos_mb'] = plot_df['position'] / 1e6
    plot_df['neg_log_p'] = -np.log10(plot_df['pval'].clip(lower=1e-20))

    fig, ax = plt.subplots(figsize=(24, 10))

    y_positions = {}
    for i, chrom in enumerate(chrom_order):
        y_positions[chrom] = i

    # Draw chromosome bars
    for chrom in chrom_order:
        y = y_positions[chrom]
        size = chrom_sizes.get(chrom, 100)
        ax.barh(y, size, height=0.6, color='#e8e8e8', edgecolor='#b0b0b0',
                linewidth=0.5, zorder=0)

    # Plot variants as ticks
    for _, row in plot_df.iterrows():
        y = y_positions.get(row['chromosome'], None)
        if y is None:
            continue
        x = row['pos_mb']
        nlp = row['neg_log_p']

        # Color by significance tier
        if row.get('sig_strict', False):
            color = COLOR_SIG
            alpha = 0.9
            lw = 1.5
        elif row.get('sig_moderate', False):
            color = COLOR_SBS2_HIGH
            alpha = 0.7
            lw = 1.2
        elif row.get('sig_suggestive', False):
            color = '#e8a87a'
            alpha = 0.5
            lw = 1.0
        elif row['pval'] < 0.05:
            color = '#d4a574'
            alpha = 0.4
            lw = 0.8
        else:
            color = COLOR_NONSIG
            alpha = 0.2
            lw = 0.5

        ax.plot([x, x], [y - 0.3, y + 0.3], color=color, alpha=alpha,
                linewidth=lw, zorder=1 + int(nlp))

    # Label significant genes
    sig_variants = plot_df[plot_df.get('sig_strict', False) == True]
    if len(sig_variants) == 0:
        sig_variants = plot_df[plot_df.get('sig_moderate', False) == True]
    if len(sig_variants) > 0:
        labeled_genes = set()
        for _, row in sig_variants.sort_values('pval').iterrows():
            gene = row['gene']
            if gene in labeled_genes:
                continue
            labeled_genes.add(gene)
            y = y_positions[row['chromosome']]
            x = row['pos_mb']
            ax.annotate(gene, (x, y + 0.35), fontsize=FONT_SIZE - 14,
                        fontweight='bold', color=COLOR_SIG,
                        ha='center', va='bottom', rotation=45)

    ax.set_yticks(range(len(chrom_order)))
    ax.set_yticklabels(chrom_order, fontsize=FONT_SIZE - 8)
    ax.set_xlabel('Position (Mb)', fontsize=FONT_SIZE)
    ax.set_title('Germline SNP Enrichment: HIGH vs LOW SBS2', fontsize=FONT_SIZE)
    ax.invert_yaxis()
    ax.spines['top'].set_visible(False)
    ax.spines['right'].set_visible(False)

    # Legend
    legend_elements = [
        mpatches.Patch(color=COLOR_SIG, alpha=0.9, label=f'BH < {BH_STRICT}'),
        mpatches.Patch(color=COLOR_SBS2_HIGH, alpha=0.7, label=f'BH < {BH_MODERATE}'),
        mpatches.Patch(color='#e8a87a', alpha=0.5, label=f'BH < {BH_SUGGESTIVE}'),
        mpatches.Patch(color='#d4a574', alpha=0.4, label='Nominal p < 0.05'),
        mpatches.Patch(color=COLOR_NONSIG, alpha=0.3, label='Not significant'),
    ]
    ax.legend(handles=legend_elements, loc='lower right', fontsize=FONT_SIZE - 8)

    plt.tight_layout()
    save_fig(fig, "Germline_Chromosome_Ideogram")

# =============================================================================
# STEP 8: KEGG PATHWAY ENRICHMENT
# =============================================================================
banner("STEP 8: Pathway Enrichment")

if len(results_df) > 0:
    # Collect genes with nominal p < 0.05 for enrichment
    nom_sig_genes = results_df[results_df['pval'] < 0.05]['gene'].unique().tolist()
    bh_sig_genes = results_df[results_df['sig_moderate'] == True]['gene'].unique().tolist() if 'sig_moderate' in results_df.columns else []

    log(f"  Genes with nominal p < 0.05: {len(nom_sig_genes)}")
    log(f"  Genes with BH < {BH_THRESHOLD}: {len(bh_sig_genes)}")

    # Try gseapy for KEGG enrichment
    try:
        import gseapy as gp

        if len(nom_sig_genes) >= 5:
            # Background: all genes tested
            background = results_df['gene'].unique().tolist()

            log(f"  Running KEGG enrichment (nominal sig genes vs background)...")
            enr = gp.enrichr(
                gene_list=nom_sig_genes,
                gene_sets='KEGG_2021_Human',
                organism='Human',
                outdir=None,
                no_plot=True,
            )

            kegg_results = enr.results
            kegg_sig = kegg_results[kegg_results['Adjusted P-value'] < 0.25]

            log(f"  KEGG terms tested: {len(kegg_results)}")
            log(f"  KEGG terms (adj p < 0.25): {len(kegg_sig)}")

            if len(kegg_results) > 0:
                log(f"\n  Top 15 KEGG pathways:")
                log(f"  {'Pathway':50s} {'Overlap':>10s} {'P-adj':>10s}")
                log(f"  {'-'*50} {'-'*10} {'-'*10}")
                for _, row in kegg_results.head(15).iterrows():
                    log(f"  {row['Term'][:50]:50s} {row['Overlap']:>10s} {row['Adjusted P-value']:>10.4f}")

            kegg_path = os.path.join(OUTPUT_DIR, "germline_KEGG_enrichment.tsv")
            kegg_results.to_csv(kegg_path, sep='\t', index=False)
            log(f"  Saved: {kegg_path}")
        else:
            log(f"  Too few significant genes ({len(nom_sig_genes)}) for enrichment")

    except ImportError:
        log(f"  gseapy not available. Install with: pip install gseapy")
        log(f"  Saving gene lists for manual enrichment instead.")

        # Save gene lists
        for label, genes in [('nominal_p005', nom_sig_genes), ('bh_sig', bh_sig_genes)]:
            if len(genes) > 0:
                gene_path = os.path.join(OUTPUT_DIR, f"germline_enrichment_genes_{label}.txt")
                with open(gene_path, 'w') as f:
                    f.write('\n'.join(genes))
                log(f"  Saved gene list: {gene_path} ({len(genes)} genes)")

# =============================================================================
# STEP 9: CROSS-REFERENCE WITH NETWORK GENES
# =============================================================================
banner("STEP 9: Cross-Reference with Network and A3 Interactors")

if len(results_df) > 0:
    # Load Harris A3 interactors from the canonical files
    harris_all_interactors = set()
    harris_a3b_interactors = set()
    harris_details = {}

    if os.path.exists(HARRIS_ALL_PATH):
        harris_df = pd.read_csv(HARRIS_ALL_PATH, sep='\t')
        harris_all_interactors = set(harris_df['gene_symbol'].values)
        harris_details = {row['gene_symbol']: {
            'baits': row.get('A3_baits', ''),
            'source': row.get('source', ''),
            'R_loop': row.get('R_loop_associated', False),
            'coIP': row.get('confirmed_coIP', False),
        } for _, row in harris_df.iterrows()}
        log(f"  Loaded Harris A3 interactors (all): {len(harris_all_interactors)} genes")
        log(f"    File: {HARRIS_ALL_PATH}")
    else:
        log(f"  WARNING: Harris interactors file not found: {HARRIS_ALL_PATH}")

    if os.path.exists(HARRIS_A3B_PATH):
        harris_a3b_df = pd.read_csv(HARRIS_A3B_PATH, sep='\t')
        harris_a3b_interactors = set(harris_a3b_df['gene_symbol'].values)
        log(f"  Loaded Harris A3B-specific interactors: {len(harris_a3b_interactors)} genes")
    else:
        log(f"  WARNING: A3B interactors file not found: {HARRIS_A3B_PATH}")

    # Cross-reference: which significant germline genes are known A3 interactors?
    tested_genes = set(results_df['gene'].unique())
    nom_sig_genes = set(results_df[results_df['pval'] < 0.05]['gene'].unique())
    bh_sig_genes = set(results_df[results_df.get('sig_moderate', False) == True]['gene'].unique())

    # All interactors among tested genes
    interactors_tested = harris_all_interactors & tested_genes
    interactors_nom_sig = harris_all_interactors & nom_sig_genes
    interactors_bh_sig = harris_all_interactors & bh_sig_genes

    a3b_tested = harris_a3b_interactors & tested_genes
    a3b_nom_sig = harris_a3b_interactors & nom_sig_genes
    a3b_bh_sig = harris_a3b_interactors & bh_sig_genes

    log(f"\n  A3 interactor cross-reference:")
    log(f"    All A3 interactors in tested genes: {len(interactors_tested)} / {len(harris_all_interactors)}")
    log(f"    All A3 interactors at nominal p<0.05: {len(interactors_nom_sig)}")
    log(f"    All A3 interactors at BH<{BH_MODERATE}: {len(interactors_bh_sig)}")
    log(f"    A3B-specific in tested genes: {len(a3b_tested)} / {len(harris_a3b_interactors)}")
    log(f"    A3B-specific at nominal p<0.05: {len(a3b_nom_sig)}")
    log(f"    A3B-specific at BH<{BH_MODERATE}: {len(a3b_bh_sig)}")

    # Detail each hit
    if interactors_nom_sig:
        log(f"\n  A3 interactors with nominal p < 0.05:")
        for gene in sorted(interactors_nom_sig):
            row = results_df[results_df['gene'] == gene].sort_values('pval').iloc[0]
            detail = harris_details.get(gene, {})
            baits = detail.get('baits', '?')
            source = detail.get('source', '?')
            coip = ' [co-IP]' if detail.get('coIP', False) else ''
            rloop = ' [R-loop]' if detail.get('R_loop', False) else ''
            log(f"    {gene:20s} p={row['pval']:.4f}, OR={row['odds_ratio']:.2f}, "
                f"baits={baits}, source={source}{coip}{rloop}")
    else:
        log(f"\n  No A3 interactors reached nominal significance")

    # Check network community overlap
    network_community_path = os.path.join(PROJECT_ROOT, "data", "FIG_2")
    community_files = [f for f in os.listdir(network_community_path)
                       if 'community' in f.lower() and f.endswith('.tsv')]  \
                       if os.path.exists(network_community_path) else []

    if community_files:
        log(f"\n  Found network community files: {community_files}")
    else:
        log(f"\n  No network community files found in {network_community_path}")
        log(f"  Cross-reference will be done after network pipeline re-run")

# =============================================================================
# STEP 10: SUMMARY
# =============================================================================
banner("PIPELINE SUMMARY")

elapsed = (time.time() - pipeline_start) / 60

n_tested = len(results_df) if len(results_df) > 0 else 0
n_nom_sig = (results_df['pval'] < 0.05).sum() if n_tested > 0 else 0
n_bh_strict = results_df['sig_strict'].sum() if n_tested > 0 and 'sig_strict' in results_df.columns else 0
n_bh_moderate = results_df['sig_moderate'].sum() if n_tested > 0 and 'sig_moderate' in results_df.columns else 0
n_bh_suggestive = results_df['sig_suggestive'].sum() if n_tested > 0 and 'sig_suggestive' in results_df.columns else 0

log(f"""
  GERMLINE SNP ENRICHMENT ANALYSIS COMPLETE

  Groups:
    HIGH SBS2: {n_per_group} patients (SBS2 >= {sbs2_high_min:.0f})
    LOW SBS2:  {n_per_group} patients (SBS2 <= {sbs2_low_max:.0f})
    Groups are EQUAL SIZE (n = {n_per_group} each)

  Germline variants:
    Tier: alt_allele_in_normal (patient's normal carries variant)
    Total germline SNPs: {len(germline):,}
    Recurrent (>= {MIN_RECURRENCE} patients): {len(recurrent_variants):,}
    Tested: {n_tested:,}

  Results:
    Nominal p < 0.05:            {n_nom_sig}
    BH < {BH_STRICT} (strict):       {n_bh_strict}
    BH < {BH_MODERATE} (moderate):     {n_bh_moderate}
    BH < {BH_SUGGESTIVE} (suggestive):   {n_bh_suggestive}

  A3 interactor cross-reference:
    Harris interactors loaded: {len(harris_all_interactors) if 'harris_all_interactors' in dir() else 'N/A'}
    A3B-specific loaded: {len(harris_a3b_interactors) if 'harris_a3b_interactors' in dir() else 'N/A'}

  Time: {elapsed:.1f} minutes
""")

# Save report
rp = os.path.join(OUTPUT_DIR, "germline_enrichment_report.txt")
with open(rp, 'w') as f:
    f.write('\n'.join(report_lines))
log(f"  Report: {rp}")

banner("GERMLINE SNP ENRICHMENT COMPLETE")
