#!/bin/bash
#SBATCH --job-name=CLUSTERCATCHER
#SBATCH --output=/master/jlehle/WORKING/LOGS/CLUSTERCATCHER_%j.out
#SBATCH --error=/master/jlehle/WORKING/LOGS/CLUSTERCATCHER_%j.err
#SBATCH --time=72:00:00
#SBATCH --mem=500G
#SBATCH --cpus-per-task=32
#SBATCH --partition=normal

# =============================================================================
# RUN_CLUSTERCATCHER_PIPELINE.sh
#
# SLURM batch script for the ClusterCatcher Single-Cell Analysis Pipeline
# Used to generate all single-cell data objects for Figure 3 (and downstream)
#
# This script:
#   1. Verifies all dependencies are installed
#   2. Configures the pipeline for HNSCC data
#   3. Runs the full ClusterCatcher pipeline via Snakemake
#
# Prerequisites (install BEFORE running this script):
#   - ClusterCatcher (https://github.com/JakeLehle/ClusterCatcher)
#   - SRAscraper (https://github.com/JakeLehle/SRAscraper)
#   - Cell Ranger >= 7.0 (https://10xgenomics.com)
#   - SComatic (https://github.com/cortes-ciriano-lab/SComatic)
#   - CytoTRACE2 (https://github.com/digitalcytometry/cytotrace2)
#   - COSMIC v3.4 SBS signatures (https://cancer.sanger.ac.uk/signatures/)
#
# Usage:
#   sbatch RUN_CLUSTERCATCHER_PIPELINE.sh
#
# =============================================================================

set -euo pipefail

echo "============================================================"
echo "ClusterCatcher Single-Cell Analysis Pipeline — Figure 3"
echo "============================================================"
echo "Job ID:     $SLURM_JOB_ID"
echo "Node:       $(hostname)"
echo "Start time: $(date)"
echo "============================================================"

# =============================================================================
# CONFIGURATION — EDIT THESE PATHS FOR YOUR SYSTEM
# =============================================================================

# Working directories
WORKING_DIR="/master/jlehle/WORKING/SC/fastq/Head_and_neck_cancer"
PAPER_DIR="/master/jlehle/WORKING/2026_NMF_PAPER"
OUTPUT_DIR="${WORKING_DIR}/ClusterCatcher_results"

# Conda environment
CONDA_ENV="ClusterCatcher"

# Reference files
CELLRANGER_REF="/master/jlehle/REFERENCES/refdata-gex-GRCh38-2020-A"
COSMIC_FILE="/master/jlehle/WORKING/SC/fastq/Head_and_neck_cancer/COSMIC_v3.4_SBS_GRCh38.txt"

# External tool directories
SCOMATIC_SCRIPTS="/master/jlehle/SOFTWARE/SComatic/scripts"
SCOMATIC_EDITING="/master/jlehle/SOFTWARE/SComatic/RNAediting/AllEditingSites.hg38.txt"
SCOMATIC_PON="/master/jlehle/SOFTWARE/SComatic/PoNs/PoN.scRNAseq.hg38.tsv"
SCOMATIC_BED="/master/jlehle/SOFTWARE/SComatic/bed_files_GRCh38/GRCh38.mappable_regions.bed"

# Sample information pickle (generated by SRAscraper)
SAMPLE_PICKLE="${WORKING_DIR}/samples.pkl"

# Pipeline parameters
THREADS=32
MEMORY_GB=500

echo ""
echo "Configuration:"
echo "  Working directory:    ${WORKING_DIR}"
echo "  Output directory:     ${OUTPUT_DIR}"
echo "  Cell Ranger ref:      ${CELLRANGER_REF}"
echo "  COSMIC signatures:    ${COSMIC_FILE}"
echo "  SComatic scripts:     ${SCOMATIC_SCRIPTS}"
echo "  Sample pickle:        ${SAMPLE_PICKLE}"
echo "  Threads:              ${THREADS}"
echo "  Memory:               ${MEMORY_GB}GB"
echo ""

# =============================================================================
# STEP 0: DEPENDENCY INSTALLATION GUIDE
# =============================================================================
# 
# The following commands document how all dependencies were installed.
# These do NOT need to be run each time — they are here for reproducibility.
#
# --- 0a. Clone and install ClusterCatcher ---
#   git clone https://github.com/JakeLehle/ClusterCatcher.git
#   cd ClusterCatcher
#   conda env create -f environment.yml
#   conda activate ClusterCatcher
#   pip install -e .
#
# --- 0b. Clone and install SRAscraper (for data download) ---
#   git clone https://github.com/JakeLehle/SRAscraper.git
#   cd SRAscraper
#   pip install -e .
#
# --- 0c. Install Cell Ranger ---
#   # Download from https://support.10xgenomics.com/single-cell-gene-expression/software/downloads/latest
#   tar -xzf cellranger-7.2.0.tar.gz
#   export PATH=/path/to/cellranger-7.2.0:$PATH
#
# --- 0d. Download Cell Ranger reference genome ---
#   wget https://cf.10xgenomics.com/supp/cell-exp/refdata-gex-GRCh38-2020-A.tar.gz
#   tar -xzf refdata-gex-GRCh38-2020-A.tar.gz
#
# --- 0e. Clone SComatic (for somatic mutation calling) ---
#   git clone https://github.com/cortes-ciriano-lab/SComatic.git
#
# --- 0f. Install CytoTRACE2 (for dysregulation detection) ---
#   git clone https://github.com/digitalcytometry/cytotrace2.git
#   cd cytotrace2/cytotrace2_python
#   pip install .
#
# --- 0g. Download COSMIC v3.4 SBS signatures ---
#   # Download from https://cancer.sanger.ac.uk/signatures/documents/2047/
#   # File: COSMIC_v3.4_SBS_GRCh38.txt
#
# =============================================================================

# =============================================================================
# STEP 1: ACTIVATE ENVIRONMENT AND VERIFY DEPENDENCIES
# =============================================================================

echo "============================================================"
echo "STEP 1: Verifying dependencies"
echo "============================================================"

source ~/anaconda3/bin/activate 2>/dev/null || conda activate ${CONDA_ENV}

# Verify ClusterCatcher
if command -v ClusterCatcher &> /dev/null; then
    echo "  ✓ ClusterCatcher: $(ClusterCatcher --version 2>&1 | head -1)"
else
    echo "  ✗ ClusterCatcher not found. Install with: pip install -e /path/to/ClusterCatcher"
    exit 1
fi

# Verify Cell Ranger
if command -v cellranger &> /dev/null; then
    echo "  ✓ Cell Ranger: $(cellranger --version 2>&1 | head -1)"
else
    echo "  ✗ Cell Ranger not found. Add to PATH."
    exit 1
fi

# Verify samtools
if command -v samtools &> /dev/null; then
    echo "  ✓ samtools: $(samtools --version | head -1)"
else
    echo "  ✗ samtools not found."
    exit 1
fi

# Verify SComatic
if [ -d "${SCOMATIC_SCRIPTS}" ]; then
    echo "  ✓ SComatic scripts: ${SCOMATIC_SCRIPTS}"
else
    echo "  ✗ SComatic scripts not found at: ${SCOMATIC_SCRIPTS}"
    exit 1
fi

# Verify reference files
if [ -d "${CELLRANGER_REF}" ]; then
    echo "  ✓ Cell Ranger reference: ${CELLRANGER_REF}"
else
    echo "  ✗ Cell Ranger reference not found."
    exit 1
fi

if [ -f "${COSMIC_FILE}" ]; then
    echo "  ✓ COSMIC signatures: ${COSMIC_FILE}"
else
    echo "  ✗ COSMIC signatures not found."
    exit 1
fi

# Verify sample pickle
if [ -f "${SAMPLE_PICKLE}" ]; then
    echo "  ✓ Sample pickle: ${SAMPLE_PICKLE}"
else
    echo "  ✗ Sample pickle not found. Run SRAscraper first."
    exit 1
fi

echo ""
echo "All dependencies verified."
echo ""

# =============================================================================
# STEP 2: GENERATE PIPELINE CONFIGURATION
# =============================================================================

echo "============================================================"
echo "STEP 2: Generating pipeline configuration"
echo "============================================================"

cd ${WORKING_DIR}

python ${WORKING_DIR}/ClusterCatcher/snakemake_wrapper/create_config.py \
    --output-dir ${OUTPUT_DIR} \
    --sample-pickle ${SAMPLE_PICKLE} \
    --cellranger-reference ${CELLRANGER_REF} \
    --threads ${THREADS} \
    --memory-gb ${MEMORY_GB} \
    --qc-mode adaptive \
    --mad-n-counts 5 \
    --mad-n-genes 5 \
    --max-mito-pct 20 \
    --min-genes 200 \
    --min-cells 20 \
    --doublet-removal \
    --doublet-rate 0.08 \
    --leiden-resolution 1.0 \
    --popv-huggingface-repo "popV/tabula_sapiens_All_Cells" \
    --popv-prediction-mode inference \
    --enable-dysregulation \
    --cytotrace2-enabled \
    --infercnv-enabled \
    --infercnv-window 250 \
    --agreement-alpha 0.5 \
    --min-correlation 0.5 \
    --enable-scomatic \
    --scomatic-scripts-dir ${SCOMATIC_SCRIPTS} \
    --scomatic-editing-sites ${SCOMATIC_EDITING} \
    --scomatic-pon-file ${SCOMATIC_PON} \
    --scomatic-bed-file ${SCOMATIC_BED} \
    --scomatic-min-cov 5 \
    --scomatic-min-cells 5 \
    --enable-signatures \
    --cosmic-file ${COSMIC_FILE} \
    --use-scree-plot \
    --core-signatures SBS2 SBS13 SBS5 \
    --hnscc-only

echo ""
echo "Configuration written to: ${OUTPUT_DIR}/config.yaml"
echo ""

# =============================================================================
# STEP 3: RUN THE CLUSTERCATCHER PIPELINE
# =============================================================================

echo "============================================================"
echo "STEP 3: Running ClusterCatcher pipeline via Snakemake"
echo "============================================================"
echo "Start time: $(date)"
echo ""

cd ${OUTPUT_DIR}

# Run the full pipeline
# --use-conda lets Snakemake manage per-rule conda environments
snakemake \
    --configfile ${OUTPUT_DIR}/config.yaml \
    --snakefile ${WORKING_DIR}/ClusterCatcher/snakemake_wrapper/Snakefile \
    --cores ${THREADS} \
    --use-conda \
    --rerun-incomplete \
    --printshellcmds \
    --keep-going \
    2>&1 | tee ${OUTPUT_DIR}/snakemake_run.log

echo ""
echo "Pipeline completed at: $(date)"
echo ""

# =============================================================================
# STEP 4: VERIFY OUTPUTS
# =============================================================================

echo "============================================================"
echo "STEP 4: Verifying pipeline outputs"
echo "============================================================"

# Check key output files
EXPECTED_FILES=(
    "${OUTPUT_DIR}/annotation/adata_annotated.h5ad"
    "${OUTPUT_DIR}/dysregulation/adata_cancer_detected.h5ad"
    "${OUTPUT_DIR}/mutations/all_samples.single_cell_genotype.filtered.tsv"
    "${OUTPUT_DIR}/mutations/CombinedCallableSites/complete_callable_sites.tsv"
    "${OUTPUT_DIR}/signatures/signature_weights_per_cell.txt"
    "${OUTPUT_DIR}/signatures/adata_final.h5ad"
)

ALL_FOUND=true
for f in "${EXPECTED_FILES[@]}"; do
    if [ -f "$f" ]; then
        SIZE=$(du -h "$f" | cut -f1)
        echo "  ✓ ${f} (${SIZE})"
    else
        echo "  ✗ MISSING: ${f}"
        ALL_FOUND=false
    fi
done

echo ""

# Check figure outputs from ClusterCatcher
echo "ClusterCatcher-generated figures (used in Figure 3a / Supplemental Figure 1):"
FIGURE_FILES=(
    "${OUTPUT_DIR}/annotation/figures/UMAP_popv_prediction.pdf"
    "${OUTPUT_DIR}/annotation/figures/UMAP_clusters.pdf"
    "${OUTPUT_DIR}/annotation/figures/UMAP_final_annotation.pdf"
    "${OUTPUT_DIR}/annotation/figures/stacked_bar_cluster_composition.pdf"
)

for f in "${FIGURE_FILES[@]}"; do
    if [ -f "$f" ]; then
        echo "  ✓ $(basename $f)"
    else
        echo "  ? $(basename $f) — may have different name, check figures directory"
    fi
done

echo ""

if [ "$ALL_FOUND" = true ]; then
    echo "All expected outputs found."
    echo ""
    echo "Next step: Run Step01_Generate_Figure3_Panels.py to produce"
    echo "  - Figure 3b panels (normalized mutations, SBS2, A3A, A3B UMAPs)"
    echo "  - Figure 3c (aggregated signature comparison)"
    echo "  - Supplemental Figure 2 (all A3 family expression UMAPs)"
else
    echo "WARNING: Some outputs are missing. Check the Snakemake log."
fi

echo ""
echo "============================================================"
echo "CLUSTERCATCHER PIPELINE COMPLETE"
echo "============================================================"
echo "End time: $(date)"
echo "============================================================"
