#!/usr/bin/env python3
"""
Step05_Fusion_Analysis.py
============================
Figure 7: Neoantigen Landscape - RNA Fusion and Chimeric Read Analysis

Re-partitions existing STAR chimeric junction data by the updated three-group
cell assignments (SBS2_HIGH, CNV_HIGH, NORMAL, 546 each), applies filter
cascade, identifies group-exclusive recurrent fusion gene pairs, runs
pathway enrichment, and performs targeted overlap analysis with spliceosome
and antigen presentation gene sets.

STAR chimeric junction files were generated by the previous STAR chimeric
pipeline (Phase5B_STAR_Chimeric_Pipeline.py / RUN_STAR_ARRAY.sh) and are
NOT regenerated here.

Filter cascade (from validated previous run):
    1. Barcode in target cells
    2. Junction types 1 and 2 (uniquely mapped chimeric reads)
    3. Alignment score ratio >= 0.80 (this_score / max_score)
    4. Both ends map to annotated genes
    5. Both genes are protein-coding
    6. Exclude known artifact loci (NRXN3, RASGRF2 hotspots)
    7. Inter-chromosomal OR long-range intra-chromosomal (>1Mb)

Inputs:
    - data/FIG_7/01_neoantigen_inputs/pipeline_config.yaml
    - STAR Chimeric.out.junction files (35 samples)
    - GRCh38 GTF gene annotations
    - data/FIG_4/01_group_selection/three_group_assignments.tsv

Outputs (to data/FIG_7/04_fusion_analysis/):
    - all_filtered_junctions.tsv       : All junctions passing filter cascade
    - per_group_junction_summary.tsv   : Per-group counts and rates
    - {group}_exclusive_pairs.tsv      : Group-exclusive recurrent gene pairs
    - {group}_exclusive_genes.txt      : Unique genes from exclusive pairs
    - shared_disease_recurrent_pairs.tsv
    - enrichment_{group}_{library}.tsv : Enrichment results
    - spliceosome_antigen_overlap.tsv  : Targeted gene set overlap
    - neoantigen_fusion_crossref.tsv   : Genes in both fusion and neoantigen lists
    - Supplemental_Table_Exclusive_Fusion_Pairs.tsv
    - filter_cascade_summary.tsv
    - step05_fusion_report.txt

Run in NETWORK conda env (needs gseapy).

Author: Jake Lehle / Claude (2026 NMF Paper)
"""

import os
import sys
import glob
import yaml
import numpy as np
import pandas as pd
from collections import defaultdict, Counter
import warnings
warnings.filterwarnings('ignore')

# =============================================================================
# CONFIGURATION
# =============================================================================
PROJECT_ROOT = "/master/jlehle/WORKING/2026_NMF_PAPER"
CONFIG_PATH = os.path.join(PROJECT_ROOT, "data/FIG_7/01_neoantigen_inputs/pipeline_config.yaml")

with open(CONFIG_PATH) as f:
    config = yaml.safe_load(f)

GROUP_PATH = os.path.join(PROJECT_ROOT, "data/FIG_4/01_group_selection/three_group_assignments.tsv")
GTF_PATH = config['reference']['gtf']

# STAR chimeric output directory (from previous pipeline run)
STAR_DIR = os.path.join(PROJECT_ROOT, "data/FIG_6/05_neoantigen/fusion_detection/star_chimeric")

# Neoantigen ranking from Step04 (for cross-reference)
MHC_DIR = config['outputs']['mhc_binding']

OUTPUT_DIR = config['outputs']['fusion_analysis']
os.makedirs(OUTPUT_DIR, exist_ok=True)

GROUPS = ['SBS2_HIGH', 'CNV_HIGH', 'NORMAL']
MIN_CELLS_RECURRENT = 2

# Filter parameters
MIN_ALN_SCORE_RATIO = 0.80
MIN_CHIMERIC_DIST = 1_000_000
VALID_JUNCTION_TYPES = {'1', '2'}  # Uniquely mapped chimeric reads

# Known artifact loci (recurrent in all groups, likely mapping artifacts)
ARTIFACT_GENES = {'NRXN3', 'RASGRF2'}

# Curated gene sets for targeted overlap analysis
SPLICEOSOME_GENES = {
    'HNRNPA1', 'HNRNPA2B1', 'HNRNPC', 'HNRNPK', 'HNRNPM',
    'SRSF1', 'SRSF2', 'SRSF3', 'SRSF5', 'SRSF7',
    'SFPQ', 'NONO', 'SNRPD2', 'SNRPC', 'SNRPA',
    'U2AF1', 'U2AF2', 'SF3B1', 'SF3A1',
    'PRPF8', 'PRPF3', 'PRPF31',
    'DDX5', 'DDX17', 'DDX39B',
    'RBMX', 'RBM25', 'PCBP1', 'PCBP2',
}

ANTIGEN_PRESENTATION_GENES = {
    # MHC Class I
    'HLA-A', 'HLA-B', 'HLA-C', 'B2M', 'TAP1', 'TAP2', 'TAPBP',
    'PSMB8', 'PSMB9', 'PSMB10', 'PSME1', 'PSME2',
    'CALR', 'CANX', 'ERAP1', 'ERAP2',
    # MHC Class II
    'CD74', 'HLA-DRA', 'HLA-DRB1', 'HLA-DPA1', 'HLA-DPB1',
    'HLA-DQA1', 'HLA-DQB1', 'CIITA',
    # Antigen processing
    'SEC61A1', 'SEC61B', 'SEC61G',
}

IMMUNE_EVASION_GENES = {
    'CD274', 'PDCD1LG2',  # PD-L1/PD-L2
    'CTLA4', 'LAG3', 'HAVCR2',  # Checkpoints
    'TGFB1', 'IL10', 'IDO1',  # Immunosuppressive
    'VEGFA', 'VEGFB',  # Angiogenic escape
}

# =============================================================================
# LOGGING
# =============================================================================
report_lines = []

def log(msg=""):
    print(msg, flush=True)
    report_lines.append(str(msg))

def log_sep(title=""):
    log("")
    log("=" * 80)
    if title:
        log(f"  {title}")
        log("=" * 80)

# =============================================================================
# STEP 0: LOAD POPULATION ASSIGNMENTS AND BUILD BARCODE MAPS
# =============================================================================
log_sep("STEP 0: Load population assignments")

groups_df = pd.read_csv(GROUP_PATH, sep='\t')
log(f"  Group assignments: {groups_df.shape}")
for grp, n in groups_df['group'].value_counts().items():
    log(f"    {grp:15s}: {n}")

bc_to_group = dict(zip(groups_df['cell_barcode'], groups_df['group']))
all_target_bcs = set(bc_to_group.keys())

# Build SRR -> {short_barcode: full_barcode} mapping
# Barcodes are formatted as: ACGTACGT-1-SRR14340900
srr_bc_map = defaultdict(dict)
for bc in all_target_bcs:
    parts = bc.split("-")
    if len(parts) >= 3:
        srr_id = parts[2]
        short_bc = f"{parts[0]}-{parts[1]}"
        srr_bc_map[srr_id][short_bc] = bc

log(f"  Total target barcodes: {len(all_target_bcs)}")
log(f"  SRR IDs with target barcodes: {len(srr_bc_map)}")

# =============================================================================
# STEP 1: LOAD GTF GENE ANNOTATIONS
# =============================================================================
log_sep("STEP 1: Load GTF gene annotations")

gene_intervals = defaultdict(list)
gene_biotype = {}
n_genes = 0
n_protein_coding = 0

with open(GTF_PATH) as f:
    for line in f:
        if line.startswith('#'):
            continue
        fields = line.strip().split('\t')
        if len(fields) < 9 or fields[2] != 'gene':
            continue

        chrom = fields[0]
        start = int(fields[3])
        end = int(fields[4])

        # Parse attributes
        gene_name = 'unknown'
        biotype = 'unknown'
        for attr in fields[8].split(';'):
            attr = attr.strip()
            if attr.startswith('gene_name'):
                gene_name = attr.split('"')[1] if '"' in attr else attr.split(' ')[-1]
            elif attr.startswith('gene_biotype') or attr.startswith('gene_type'):
                biotype = attr.split('"')[1] if '"' in attr else attr.split(' ')[-1]

        gene_intervals[chrom].append((start, end, gene_name))
        gene_biotype[gene_name] = biotype
        n_genes += 1
        if biotype == 'protein_coding':
            n_protein_coding += 1

log(f"  Loaded {n_genes} gene annotations across {len(gene_intervals)} chromosomes")
log(f"  Protein-coding genes: {n_protein_coding}")


def pos_to_gene(chrom, pos):
    """Map a genomic position to a gene name."""
    for s, e, name in gene_intervals.get(chrom, []):
        if s <= pos <= e:
            return name
    return None


def extract_barcode(fields, target_bcs_short):
    """
    Extract cell barcode from STAR chimeric junction fields.
    Tries multiple strategies: CB:Z: tag in extra fields, read name parsing.
    Returns (short_barcode, full_barcode) or (None, None).
    """
    # Strategy 1: CB:Z: tag in extra fields (field 19+)
    for fi in range(19, len(fields)):
        if fields[fi].startswith('CB:Z:'):
            cb = fields[fi][5:]
            # Try direct match
            if cb in target_bcs_short:
                return cb, target_bcs_short[cb]
            # Try with -1 suffix
            cb_suffixed = cb + '-1' if '-' not in cb else cb
            if cb_suffixed in target_bcs_short:
                return cb_suffixed, target_bcs_short[cb_suffixed]

    # Strategy 2: Check all fields for 16bp barcode-like strings
    for fi in range(14, len(fields)):
        field = fields[fi]
        if len(field) == 16 and field.isalpha():
            short = field + '-1'
            if short in target_bcs_short:
                return short, target_bcs_short[short]
        if len(field) == 18 and '-' in field:
            if field in target_bcs_short:
                return field, target_bcs_short[field]

    # Strategy 3: Parse read name for barcode
    if len(fields) > 9:
        rname = fields[9]
        for sep in ['_', ':', '|']:
            for part in rname.split(sep):
                if len(part) == 16 and part.isalpha():
                    short = part + '-1'
                    if short in target_bcs_short:
                        return short, target_bcs_short[short]
                if '-' in part and part in target_bcs_short:
                    return part, target_bcs_short[part]

    return None, None

# =============================================================================
# STEP 2: PARSE STAR CHIMERIC JUNCTION FILES
# =============================================================================
log_sep("STEP 2: Parse STAR Chimeric.out.junction files")

# Find junction files
junction_files = sorted(glob.glob(os.path.join(STAR_DIR, "SRR*", "Chimeric.out.junction")))
log(f"  Found {len(junction_files)} junction files")

if len(junction_files) == 0:
    log(f"  ERROR: No junction files found in {STAR_DIR}")
    log(f"  Expected path: {STAR_DIR}/SRR*/Chimeric.out.junction")
    log(f"  The STAR chimeric pipeline must be run first.")
    sys.exit(1)

# Filter cascade counters
cascade = Counter()
all_junctions = []

for jfile in junction_files:
    srr_id = os.path.basename(os.path.dirname(jfile))
    target_bcs = srr_bc_map.get(srr_id, {})

    n_total = 0
    n_in_target = 0
    n_passed = 0

    with open(jfile) as f:
        for line in f:
            if line.startswith('#') or line.startswith('chr_donorA'):
                continue

            fields = line.strip().split('\t')
            if len(fields) < 15:
                continue

            n_total += 1
            cascade['total'] += 1

            # Filter 1: Junction type (uniquely mapped)
            jtype = fields[6]
            if jtype not in VALID_JUNCTION_TYPES:
                continue
            cascade['valid_junction_type'] += 1

            # Extract barcode
            short_bc, full_bc = extract_barcode(fields, target_bcs)
            if full_bc is None:
                continue
            n_in_target += 1
            cascade['in_target'] += 1

            # Filter 2: Alignment score ratio
            try:
                max_score = float(fields[15])
                this_score = float(fields[17])
                if max_score > 0 and (this_score / max_score) < MIN_ALN_SCORE_RATIO:
                    continue
            except (ValueError, IndexError):
                continue
            cascade['good_aln_score'] += 1

            # Map positions to genes
            chrA, posA = fields[0], int(fields[1])
            chrB, posB = fields[3], int(fields[4])

            geneA = pos_to_gene(chrA, posA)
            geneB = pos_to_gene(chrB, posB)

            # Filter 3: Both ends map to genes
            if geneA is None or geneB is None:
                continue
            cascade['both_genic'] += 1

            # Filter 4: Both genes are protein-coding
            if gene_biotype.get(geneA, '') != 'protein_coding' or \
               gene_biotype.get(geneB, '') != 'protein_coding':
                continue
            cascade['both_protein_coding'] += 1

            # Filter 5: Exclude known artifacts
            pair_set = {geneA, geneB}
            if pair_set & ARTIFACT_GENES:
                continue
            cascade['no_artifacts'] += 1

            # Filter 6: Inter-chromosomal or long-range intra-chromosomal
            if chrA == chrB:
                dist = abs(posB - posA)
                if dist < MIN_CHIMERIC_DIST:
                    continue
            cascade['inter_or_longrange'] += 1

            n_passed += 1
            group = bc_to_group.get(full_bc, 'unknown')

            all_junctions.append({
                'srr_id': srr_id,
                'barcode': full_bc,
                'group': group,
                'chrA': chrA, 'posA': posA, 'geneA': geneA,
                'chrB': chrB, 'posB': posB, 'geneB': geneB,
                'junction_type': jtype,
                'aln_score_ratio': round(this_score / max_score, 3) if max_score > 0 else 0,
                'is_interchrom': chrA != chrB,
            })

    log(f"  {srr_id}: {n_total:,} total -> {n_in_target:,} target -> {n_passed} passed")

# Filter cascade summary
log(f"\n  Filter cascade:")
cascade_steps = ['total', 'valid_junction_type', 'in_target', 'good_aln_score',
                 'both_genic', 'both_protein_coding', 'no_artifacts', 'inter_or_longrange']
for step in cascade_steps:
    count = cascade.get(step, 0)
    pct = 100 * count / cascade.get('total', 1)
    log(f"    {step:25s}: {count:>12,} ({pct:7.3f}%)")

# Save filtered junctions
jdf = pd.DataFrame(all_junctions)
junctions_path = os.path.join(OUTPUT_DIR, "all_filtered_junctions.tsv")
jdf.to_csv(junctions_path, sep='\t', index=False)
log(f"\n  Saved {len(jdf)} junctions to {junctions_path}")

# Save cascade summary
cascade_df = pd.DataFrame([{'step': s, 'count': cascade.get(s, 0),
                             'pct': 100 * cascade.get(s, 0) / cascade.get('total', 1)}
                            for s in cascade_steps])
cascade_df.to_csv(os.path.join(OUTPUT_DIR, "filter_cascade_summary.tsv"), sep='\t', index=False)

# Per-group junction counts
log(f"\n  Per-group junction counts:")
for grp in GROUPS:
    n = (jdf['group'] == grp).sum() if len(jdf) > 0 else 0
    n_cells = len(groups_df[groups_df['group'] == grp])
    rate = n / n_cells if n_cells > 0 else 0
    log(f"    {grp:15s}: {n:5d} junctions ({rate:.1f} per cell)")

# Per-group summary table
group_summary = []
for grp in GROUPS:
    grp_j = jdf[jdf['group'] == grp] if len(jdf) > 0 else pd.DataFrame()
    n_cells = len(groups_df[groups_df['group'] == grp])
    bcs_with = grp_j['barcode'].nunique() if len(grp_j) > 0 else 0
    group_summary.append({
        'group': grp,
        'n_cells': n_cells,
        'total_junctions': len(grp_j),
        'junctions_per_cell': len(grp_j) / n_cells if n_cells > 0 else 0,
        'cells_with_junctions': bcs_with,
        'pct_cells_with': 100 * bcs_with / n_cells if n_cells > 0 else 0,
        'interchrom': grp_j['is_interchrom'].sum() if len(grp_j) > 0 else 0,
        'longrange_intra': (~grp_j['is_interchrom']).sum() if len(grp_j) > 0 else 0,
    })
pd.DataFrame(group_summary).to_csv(
    os.path.join(OUTPUT_DIR, "per_group_junction_summary.tsv"), sep='\t', index=False)

# =============================================================================
# STEP 3: GROUP-EXCLUSIVE RECURRENT GENE PAIRS
# =============================================================================
log_sep("STEP 3: Group-exclusive recurrent gene pairs")

if len(jdf) == 0:
    log("  No junctions to analyze")
else:
    # Build sorted gene pair for each junction
    jdf['_pair'] = jdf.apply(
        lambda r: tuple(sorted([str(r['geneA']), str(r['geneB'])])), axis=1)

    # Count cells per pair per group
    pair_cells = {g: defaultdict(set) for g in GROUPS}
    pair_counts = {g: Counter() for g in GROUPS}

    for _, row in jdf.iterrows():
        grp = row['group']
        if grp not in GROUPS:
            continue
        pair_cells[grp][row['_pair']].add(row['barcode'])
        pair_counts[grp][row['_pair']] += 1

    for g in GROUPS:
        n_unique = len(pair_counts[g])
        n_recurrent = sum(1 for p in pair_cells[g] if len(pair_cells[g][p]) >= MIN_CELLS_RECURRENT)
        log(f"  {g}: {n_unique} unique pairs, {n_recurrent} recurrent (>={MIN_CELLS_RECURRENT} cells)")

    # Identify recurrent pairs per group
    recurrent = {}
    for grp in GROUPS:
        recurrent[grp] = {p for p, cells in pair_cells[grp].items()
                          if len(cells) >= MIN_CELLS_RECURRENT}

    # Exclusive pairs (recurrent in one group, not recurrent in others)
    exclusive = {}
    exclusive_genes = {}
    for grp in GROUPS:
        others = set().union(*(recurrent[g] for g in GROUPS if g != grp))
        exclusive[grp] = recurrent[grp] - others
        log(f"  {grp} exclusive: {len(exclusive[grp])} pairs")

        # Save exclusive pairs
        rows = [{'geneA': p[0], 'geneB': p[1],
                 'n_cells': len(pair_cells[grp][p]),
                 'n_events': pair_counts[grp][p]}
                for p in sorted(exclusive[grp])]
        edf = pd.DataFrame(rows).sort_values('n_cells', ascending=False) if rows else pd.DataFrame()
        edf.to_csv(os.path.join(OUTPUT_DIR, f"{grp}_exclusive_pairs.tsv"), sep='\t', index=False)

        # Top exclusive pairs
        log(f"\n  {grp}: {len(edf)} exclusive pairs saved")
        for _, r in edf.head(10).iterrows():
            log(f"    {r['geneA']} -- {r['geneB']} ({r['n_cells']} cells, {r['n_events']} events)")

        # Unique genes from exclusive pairs
        genes = set()
        for p in exclusive[grp]:
            genes.update(p)
        exclusive_genes[grp] = sorted(genes)
        with open(os.path.join(OUTPUT_DIR, f"{grp}_exclusive_genes.txt"), 'w') as f:
            f.write('\n'.join(exclusive_genes[grp]))
        log(f"  {grp}: {len(exclusive_genes[grp])} unique genes from exclusive pairs")

    # Supplemental table (all exclusive pairs from all groups)
    all_excl_rows = []
    for grp in GROUPS:
        for p in exclusive[grp]:
            all_excl_rows.append({
                'group': grp, 'geneA': p[0], 'geneB': p[1],
                'n_cells': len(pair_cells[grp][p]),
                'n_events': pair_counts[grp][p],
            })
    supp_df = pd.DataFrame(all_excl_rows).sort_values(['group', 'n_cells'], ascending=[True, False])
    supp_df.to_csv(os.path.join(OUTPUT_DIR, "Supplemental_Table_Exclusive_Fusion_Pairs.tsv"),
                   sep='\t', index=False)
    log(f"\n  Supplemental table: {len(supp_df)} total exclusive pairs")

    # Shared recurrent pairs between disease groups
    shared_disease = recurrent.get('SBS2_HIGH', set()) & recurrent.get('CNV_HIGH', set())
    log(f"\n  SBS2_HIGH and CNV_HIGH shared recurrent pairs: {len(shared_disease)}")
    if shared_disease:
        shared_rows = []
        for p in shared_disease:
            shared_rows.append({
                'geneA': p[0], 'geneB': p[1],
                'SBS2_HIGH_cells': len(pair_cells['SBS2_HIGH'][p]),
                'CNV_HIGH_cells': len(pair_cells['CNV_HIGH'][p]),
            })
        shared_df = pd.DataFrame(shared_rows).sort_values('SBS2_HIGH_cells', ascending=False)
        shared_df.to_csv(os.path.join(OUTPUT_DIR, "shared_disease_recurrent_pairs.tsv"),
                         sep='\t', index=False)
        for _, r in shared_df.head(10).iterrows():
            log(f"    {r['geneA']} -- {r['geneB']} "
                f"(SBS2:{r['SBS2_HIGH_cells']}, CNV:{r['CNV_HIGH_cells']})")

# =============================================================================
# STEP 4: ENRICHMENT ANALYSIS
# =============================================================================
log_sep("STEP 4: Enrichment analysis (gseapy)")

try:
    import gseapy as gp
    HAS_GSEAPY = True
    log("  gseapy loaded")
except ImportError:
    HAS_GSEAPY = False
    log("  gseapy not available, skipping enrichment")

if HAS_GSEAPY and len(jdf) > 0:
    LIBS = ['KEGG_2021_Human', 'Reactome_2022', 'GO_Biological_Process_2023']

    for grp in ['SBS2_HIGH', 'CNV_HIGH']:
        gl = exclusive_genes.get(grp, [])
        if len(gl) < 5:
            log(f"\n  {grp}: {len(gl)} genes, too few for enrichment")
            continue

        log(f"\n  --- {grp} ({len(gl)} genes) ---")
        for lib in LIBS:
            try:
                enr = gp.enrichr(gene_list=gl, gene_sets=lib, organism='human',
                                 outdir=None, no_plot=True)
                res = enr.results
                sig = res[res['Adjusted P-value'] < 0.05]
                log(f"    {lib}: {len(sig)} significant / {len(res)} total")

                res.to_csv(os.path.join(OUTPUT_DIR,
                    f"{grp}_enrichment_{lib.split('_')[0]}.tsv"), sep='\t', index=False)

                show = sig if len(sig) > 0 else res
                for _, r in show.head(5).iterrows():
                    pre = "" if r['Adjusted P-value'] < 0.05 else "(ns) "
                    log(f"      {pre}{r['Term']}: p_adj={r['Adjusted P-value']:.2e}, "
                        f"genes={r['Genes']}")
            except Exception as e:
                log(f"    {lib}: ERROR - {e}")

# =============================================================================
# STEP 5: SPLICEOSOME AND ANTIGEN PRESENTATION OVERLAP
# =============================================================================
log_sep("STEP 5: Spliceosome and antigen presentation gene set overlap")

if len(jdf) > 0:
    overlap_rows = []

    for grp in ['SBS2_HIGH', 'CNV_HIGH']:
        gs = set(exclusive_genes.get(grp, []))

        splice_hit = sorted(gs & SPLICEOSOME_GENES)
        antigen_hit = sorted(gs & ANTIGEN_PRESENTATION_GENES)
        evasion_hit = sorted(gs & IMMUNE_EVASION_GENES)

        log(f"\n  {grp}:")
        log(f"    Spliceosome genes in exclusive fusions ({len(splice_hit)}): {splice_hit}")
        log(f"    Antigen presentation genes ({len(antigen_hit)}): {antigen_hit}")
        log(f"    Immune evasion genes ({len(evasion_hit)}): {evasion_hit}")

        # For each hit, show which fusion pairs it appears in
        if splice_hit or antigen_hit or evasion_hit:
            log(f"\n    Fusion pair context:")
            all_hits = sorted(set(splice_hit + antigen_hit + evasion_hit))
            for gene in all_hits:
                partners = []
                for p in exclusive[grp]:
                    if gene in p:
                        partner = p[1] if p[0] == gene else p[0]
                        n = len(pair_cells[grp][p])
                        partners.append(f"{partner} ({n} cells)")
                category = []
                if gene in SPLICEOSOME_GENES:
                    category.append('spliceosome')
                if gene in ANTIGEN_PRESENTATION_GENES:
                    category.append('antigen_pres')
                if gene in IMMUNE_EVASION_GENES:
                    category.append('immune_evasion')
                log(f"      {gene} [{', '.join(category)}]: partners = {', '.join(partners)}")

        for gene in splice_hit:
            overlap_rows.append({'group': grp, 'gene': gene, 'category': 'spliceosome'})
        for gene in antigen_hit:
            overlap_rows.append({'group': grp, 'gene': gene, 'category': 'antigen_presentation'})
        for gene in evasion_hit:
            overlap_rows.append({'group': grp, 'gene': gene, 'category': 'immune_evasion'})

    if overlap_rows:
        overlap_df = pd.DataFrame(overlap_rows)
        overlap_df.to_csv(os.path.join(OUTPUT_DIR, "spliceosome_antigen_overlap.tsv"),
                          sep='\t', index=False)
        log(f"\n  Saved: spliceosome_antigen_overlap.tsv ({len(overlap_df)} hits)")

# =============================================================================
# STEP 6: CROSS-REFERENCE WITH NEOANTIGEN RANKINGS
# =============================================================================
log_sep("STEP 6: Cross-reference fusions with neoantigen targets")

crossref_rows = []

for grp in ['SBS2_HIGH', 'CNV_HIGH']:
    # Load neoantigen ranking from Step04
    ranking_path = os.path.join(MHC_DIR, f"{grp}_expression_weighted_ranking.tsv")
    if not os.path.exists(ranking_path):
        log(f"  {grp}: No neoantigen ranking found at {ranking_path}")
        continue

    ranking = pd.read_csv(ranking_path, sep='\t')
    neo_genes = set(ranking['gene'])
    fusion_genes_grp = set(exclusive_genes.get(grp, []))

    overlap = neo_genes & fusion_genes_grp
    log(f"\n  {grp}:")
    log(f"    Neoantigen genes:        {len(neo_genes)}")
    log(f"    Exclusive fusion genes:  {len(fusion_genes_grp)}")
    log(f"    Overlap:                 {len(overlap)}")

    if overlap:
        log(f"\n    Genes in BOTH neoantigen and fusion lists:")
        for gene in sorted(overlap):
            neo_row = ranking[ranking['gene'] == gene].iloc[0]
            neo_rank = neo_row['rank']
            neo_score = neo_row['composite_score']
            neo_ic50 = neo_row['best_ic50']

            # Find fusion partners
            partners = []
            for p in exclusive[grp]:
                if gene in p:
                    partner = p[1] if p[0] == gene else p[0]
                    n = len(pair_cells[grp][p])
                    partners.append(f"{partner}({n})")

            log(f"      {gene}: neo_rank={neo_rank}, composite={neo_score:.4f}, "
                f"IC50={neo_ic50:.1f}, fusion_partners=[{', '.join(partners)}]")

            crossref_rows.append({
                'group': grp, 'gene': gene,
                'neoantigen_rank': neo_rank,
                'composite_score': neo_score,
                'best_ic50': neo_ic50,
                'fusion_partners': '; '.join(partners),
            })

if crossref_rows:
    crossref_df = pd.DataFrame(crossref_rows)
    crossref_df.to_csv(os.path.join(OUTPUT_DIR, "neoantigen_fusion_crossref.tsv"),
                       sep='\t', index=False)
    log(f"\n  Saved: neoantigen_fusion_crossref.tsv ({len(crossref_df)} genes)")
else:
    log(f"\n  No neoantigen-fusion overlap found (or rankings not yet generated)")

# =============================================================================
# SAVE REPORT
# =============================================================================
log_sep("STEP 05 COMPLETE")
log(f"  NEXT: Generate_Figure7_Panels.py")

report_path = os.path.join(OUTPUT_DIR, "step05_fusion_report.txt")
with open(report_path, 'w') as f:
    f.write('\n'.join(report_lines))
log(f"  Report: {report_path}")
