#!/usr/bin/env python3
"""
Extract_Harris_A3_Interactors.py
================================

Extracts high-confidence APOBEC3 protein interactors from two Harris lab
publications and generates a combined reference gene list for cross-referencing
with network communities in Figure 4.

Source 1: Jang et al. (2024) Mol Cell Proteomics 23:100755
  "Protein Interaction Map of APOBEC3 Enzyme Family Reveals
   Deamination-Independent Role in Cellular Function"
  - Supplementary Table: mmc15.xlsx (AP-MS with SAINT/CompPASS scoring)
  - Full A3 family interactome (A3A through A3H)

Source 2: McCann et al. (2023) Nat Genet 55:1721-1734
  "APOBEC3B regulates R-loops and promotes transcription-associated
   mutagenesis in cancer"
  - ~24 high-confidence A3B interactors from AP-MS (Figure 1a,b)
  - 60% overlap with S9.6 (R-loop) AP-MS datasets
  - Manually curated from paper figures and text

Filtering criteria (Jang et al.):
  Step 1: SAINT BFDR < 0.05
  Step 2: CompPASS wd_percentile_perBait >= 0.90
  (Two-step filtering as described in their Methods)

Output:
  Harris_A3_interactors.txt — combined, deduplicated gene list with source
  annotations and functional categories

Usage:
  Place mmc15.xlsx in the same directory, then run:
    conda run -n NETWORK python Extract_Harris_A3_Interactors.py

Author: Jake Lehle
Texas Biomedical Research Institute
"""

import os
import sys
import pandas as pd
import numpy as np
from datetime import datetime

# =============================================================================
# CONFIGURATION
# =============================================================================

# Input
MMC15_PATH = "/master/jlehle/WORKING/2026_NMF_PAPER/data/FIG_4/00_input/mmc15.xlsx"

# Output
OUTPUT_DIR = "/master/jlehle/WORKING/2026_NMF_PAPER/data/FIG_4/00_input"
OUTPUT_FILE = os.path.join(OUTPUT_DIR, "Harris_A3_interactors.txt")

# Filtering thresholds (matching Jang et al. Methods)
BFDR_THRESHOLD = 0.05
WD_PERCENTILE_THRESHOLD = 0.90

# UniProt → Gene Symbol mapping file
# Generated by Convert_Uniprot_to_Gene_Symbol.py from all unique UniProt
# accessions in mmc15.xlsx, converted via the UniProt ID Mapping API.
UNIPROT_MAPPING_FILE = "/master/jlehle/WORKING/2026_NMF_PAPER/scripts/uniprot_to_gene_symbol_mapping.tsv"

# These will be populated at runtime from the mapping file
UNIPROT_ENTRY_TO_GENE = {}   # UniProt_Entry_Name → Gene_Symbol
UNIPROT_ACC_TO_GENE = {}     # UniProt_Accession → Gene_Symbol


# =============================================================================
# McCANN et al. 2023 Nature Genetics — A3B Interactors
# =============================================================================
# From Supplementary Table 1, Layer 1: Proteomic data from A3B and control
# AP-MS experiments. 25 proteins total (including APOBEC3A and APOBEC3B as
# bait/self); 23 non-self interactors.
#
# These high-confidence A3B-SF interactors were identified in biologically
# independent AP-MS experiments. 60% had been found independently in S9.6
# (R-loop) AP-MS datasets, linking A3B to R-loop biology.
#
# Source: McCann et al. (2023) Nat Genet 55:1721-1734
#         Supplementary Table 1, Layer 1

MCCANN_2023_A3B_INTERACTORS = {
    # Bait / self (excluded from final interactor list)
    # 'APOBEC3A':  — self/family
    # 'APOBEC3B':  — bait
    #
    # 23 high-confidence A3B interactors:
    'CDK4':      {'category': 'cell_cycle_kinase',    'confirmed_coIP': False},
    'CPSF7':     {'category': 'RNA_processing',       'confirmed_coIP': False},
    'FMR1':      {'category': 'RNA_binding',          'confirmed_coIP': False},
    'FUBP1':     {'category': 'transcription',        'confirmed_coIP': False},
    'GEMIN5':    {'category': 'snRNP_assembly',       'confirmed_coIP': False},
    'HNRNPH2':   {'category': 'hnRNP',               'confirmed_coIP': False},
    'HNRNPUL1':  {'category': 'hnRNP',               'confirmed_coIP': True},
    'MAP4':      {'category': 'cytoskeleton',         'confirmed_coIP': False},
    'MMTAG2':    {'category': 'nuclear',              'confirmed_coIP': False},
    'MOV10':     {'category': 'RNA_helicase',         'confirmed_coIP': False},
    'PDCD5':     {'category': 'apoptosis',            'confirmed_coIP': False},
    'RBM3':      {'category': 'RNA_binding',          'confirmed_coIP': False},
    'RBM8A':     {'category': 'exon_junction_complex','confirmed_coIP': False},
    'RCC2':      {'category': 'chromatin',            'confirmed_coIP': False},
    'SAFB':      {'category': 'chromatin',            'confirmed_coIP': False},
    'SF3B2':     {'category': 'splicing',             'confirmed_coIP': False},
    'SKIV2L2':   {'category': 'RNA_exosome',          'confirmed_coIP': False},
    'SNRNP200':  {'category': 'splicing',             'confirmed_coIP': False},
    'SNRPB2':    {'category': 'splicing',             'confirmed_coIP': False},
    'SRSF10':    {'category': 'splicing',             'confirmed_coIP': False},
    'SRSF7':     {'category': 'splicing',             'confirmed_coIP': False},
    'USP7':      {'category': 'deubiquitinase',       'confirmed_coIP': False},
    'ZFR':       {'category': 'RNA_binding',          'confirmed_coIP': False},
}

# =============================================================================
# HELPER FUNCTIONS
# =============================================================================

def log(msg):
    timestamp = datetime.now().strftime('%H:%M:%S')
    print(f"[{timestamp}] {msg}", flush=True)


def load_uniprot_mapping():
    """
    Load the UniProt → Gene Symbol mapping from the TSV file generated
    by Convert_Uniprot_to_Gene_Symbol.py.
    
    Populates both UNIPROT_ENTRY_TO_GENE and UNIPROT_ACC_TO_GENE globals.
    
    Expected columns: UniProt_Accession, UniProt_Entry_Name, Gene_Symbol
    """
    global UNIPROT_ENTRY_TO_GENE, UNIPROT_ACC_TO_GENE

    if not os.path.exists(UNIPROT_MAPPING_FILE):
        log(f"ERROR: UniProt mapping file not found: {UNIPROT_MAPPING_FILE}")
        log("  Run Convert_Uniprot_to_Gene_Symbol.py first to generate it.")
        sys.exit(1)

    mapping_df = pd.read_csv(UNIPROT_MAPPING_FILE, sep='\t')
    log(f"  Loaded UniProt mapping: {len(mapping_df):,} entries")
    log(f"  Columns: {list(mapping_df.columns)}")

    # Build both lookup dictionaries
    for _, row in mapping_df.iterrows():
        acc = str(row['UniProt_Accession']).strip()
        entry = str(row['UniProt_Entry_Name']).strip()
        symbol = str(row['Gene_Symbol']).strip()

        if symbol and symbol != 'nan':
            UNIPROT_ENTRY_TO_GENE[entry] = symbol
            UNIPROT_ACC_TO_GENE[acc] = symbol

    log(f"  Entry name → Gene Symbol: {len(UNIPROT_ENTRY_TO_GENE):,} mappings")
    log(f"  Accession → Gene Symbol:  {len(UNIPROT_ACC_TO_GENE):,} mappings")


def convert_to_gene_symbol(entry_name=None, accession=None):
    """
    Convert a UniProt entry name or accession to a gene symbol using the
    mapping file. Tries entry name first, then accession.
    
    Returns None if no mapping is found (no guessing, no hallucination).
    """
    # Try entry name lookup
    if entry_name and str(entry_name) in UNIPROT_ENTRY_TO_GENE:
        return UNIPROT_ENTRY_TO_GENE[str(entry_name)]

    # Try accession lookup
    if accession and str(accession) in UNIPROT_ACC_TO_GENE:
        return UNIPROT_ACC_TO_GENE[str(accession)]

    # No mapping found — return None so caller can handle it
    return None


# =============================================================================
# MAIN PIPELINE
# =============================================================================

def main():
    log("=" * 80)
    log("EXTRACTING HARRIS LAB A3 INTERACTORS")
    log("=" * 80)

    os.makedirs(OUTPUT_DIR, exist_ok=True)

    # -----------------------------------------------------------------
    # LOAD UNIPROT MAPPING FILE
    # -----------------------------------------------------------------
    log(f"\n{'='*60}")
    log("LOADING UNIPROT → GENE SYMBOL MAPPING")
    log(f"{'='*60}")
    load_uniprot_mapping()

    # -----------------------------------------------------------------
    # SOURCE 1: Jang et al. 2024 (mmc15.xlsx)
    # -----------------------------------------------------------------
    log(f"\n{'='*60}")
    log("SOURCE 1: Jang et al. (2024) Mol Cell Proteomics")
    log(f"{'='*60}")

    if not os.path.exists(MMC15_PATH):
        log(f"  ERROR: mmc15.xlsx not found at {MMC15_PATH}")
        log(f"  Please place mmc15.xlsx in: {OUTPUT_DIR}/")
        sys.exit(1)

    log(f"  Loading: {MMC15_PATH}")
    df = pd.read_excel(MMC15_PATH, sheet_name='Saint and CompPASS Scores')
    df = df.dropna(subset=['Bait.x'])
    log(f"  Total interactions: {len(df):,}")

    # Apply two-step filtering
    log(f"\n  Filtering: BFDR < {BFDR_THRESHOLD} AND wd_percentile_perBait >= {WD_PERCENTILE_THRESHOLD}")
    hc = df[(df['BFDR'] < BFDR_THRESHOLD) & (df['wd_percentile_perBait'] >= WD_PERCENTILE_THRESHOLD)]
    log(f"  High-confidence interactions: {len(hc):,}")

    # Extract per-bait interactors
    jang_interactors = {}
    unmapped_entries = set()
    a3_baits = ['A3A', 'A3B', 'A3C', 'A3D', 'A3F', 'A3G', 'A3HhapI', 'A3HhapII']

    for bait_prefix in a3_baits:
        # Match both NT and +RNAse conditions
        mask = hc['Bait.x'].str.startswith(bait_prefix, na=False)
        subset = hc[mask]

        # Get unique prey rows (need both entry name and accession for lookup)
        prey_rows = subset[['Prey.x', 'PreyGene']].drop_duplicates()

        for _, prey_row in prey_rows.iterrows():
            accession = str(prey_row['Prey.x']).strip()
            entry_name = str(prey_row['PreyGene']).strip()

            # Look up gene symbol using the mapping file
            symbol = convert_to_gene_symbol(entry_name=entry_name, accession=accession)

            if symbol is None:
                unmapped_entries.add((accession, entry_name))
                continue

            # Skip self-interactions (A3 family members as prey)
            if symbol.startswith('APOBEC3'):
                continue

            if symbol not in jang_interactors:
                jang_interactors[symbol] = {
                    'baits': set(),
                    'uniprot_accession': accession,
                    'uniprot_entry': entry_name,
                    'source': 'Jang_2024',
                }
            # Normalize bait name (collapse RNAse conditions and haplotypes)
            bait_clean = bait_prefix.replace('_RNAse', '').replace('hapI', 'H').replace('hapII', 'H')
            if bait_clean.startswith('A3Hhap'):
                bait_clean = 'A3H'
            jang_interactors[symbol]['baits'].add(bait_clean)

    log(f"\n  Unique interactor genes (Jang 2024): {len(jang_interactors):,}")

    if unmapped_entries:
        log(f"\n  WARNING: {len(unmapped_entries)} prey proteins could not be mapped to gene symbols:")
        for acc, entry in sorted(unmapped_entries):
            log(f"    {acc} ({entry}) — not found in {UNIPROT_MAPPING_FILE}")
        log(f"  These proteins are EXCLUDED from the output. If they are important,")
        log(f"  add them to the mapping file and re-run.")

    # Report per-A3 member counts
    log(f"\n  Per-A3 member interactor counts:")
    for bait_prefix in ['A3A', 'A3B', 'A3C', 'A3D', 'A3F', 'A3G', 'A3H']:
        count = sum(1 for v in jang_interactors.values()
                    if bait_prefix in v['baits'] or
                    any(b.startswith(bait_prefix) for b in v['baits']))
        log(f"    {bait_prefix}: {count}")

    # -----------------------------------------------------------------
    # SOURCE 2: McCann et al. 2023 Nature Genetics (manually curated)
    # -----------------------------------------------------------------
    log(f"\n{'='*60}")
    log("SOURCE 2: McCann et al. (2023) Nature Genetics")
    log(f"{'='*60}")
    log(f"  Curated A3B interactors: {len(MCCANN_2023_A3B_INTERACTORS)}")

    rloop_count = sum(1 for v in MCCANN_2023_A3B_INTERACTORS.values()
                      if 'R-loop' in v['category'])
    log(f"  R-loop associated: {rloop_count} ({100*rloop_count/len(MCCANN_2023_A3B_INTERACTORS):.0f}%)")

    coip_count = sum(1 for v in MCCANN_2023_A3B_INTERACTORS.values()
                     if v['confirmed_coIP'])
    log(f"  Confirmed by co-IP: {coip_count}")

    # -----------------------------------------------------------------
    # COMBINE AND DEDUPLICATE
    # -----------------------------------------------------------------
    log(f"\n{'='*60}")
    log("COMBINING SOURCES")
    log(f"{'='*60}")

    combined = {}

    # Add Jang interactors
    for symbol, info in jang_interactors.items():
        combined[symbol] = {
            'gene_symbol': symbol,
            'baits': info['baits'],
            'source': {'Jang_2024'},
            'category': 'AP-MS',
            'R_loop_associated': False,
            'confirmed_coIP': False,
        }

    # Add/merge McCann interactors
    for symbol, info in MCCANN_2023_A3B_INTERACTORS.items():
        if symbol in combined:
            combined[symbol]['source'].add('McCann_2023')
            combined[symbol]['R_loop_associated'] = 'R-loop' in info['category']
            combined[symbol]['confirmed_coIP'] = info['confirmed_coIP']
            combined[symbol]['baits'].add('A3B')
        else:
            combined[symbol] = {
                'gene_symbol': symbol,
                'baits': {'A3B'},
                'source': {'McCann_2023'},
                'category': info['category'],
                'R_loop_associated': 'R-loop' in info['category'],
                'confirmed_coIP': info['confirmed_coIP'],
            }

    log(f"  Total unique interactors (combined): {len(combined)}")

    # Count overlaps
    both = sum(1 for v in combined.values() if len(v['source']) > 1)
    jang_only = sum(1 for v in combined.values() if v['source'] == {'Jang_2024'})
    mccann_only = sum(1 for v in combined.values() if v['source'] == {'McCann_2023'})
    log(f"  In both sources: {both}")
    log(f"  Jang 2024 only: {jang_only}")
    log(f"  McCann 2023 only: {mccann_only}")

    # A3B-specific interactors (most relevant for our paper)
    a3b_interactors = {k: v for k, v in combined.items() if 'A3B' in v['baits']}
    log(f"\n  A3B-specific interactors: {len(a3b_interactors)}")

    # -----------------------------------------------------------------
    # WRITE OUTPUT
    # -----------------------------------------------------------------
    log(f"\n{'='*60}")
    log("WRITING OUTPUT")
    log(f"{'='*60}")

    rows = []
    for symbol in sorted(combined.keys()):
        info = combined[symbol]
        rows.append({
            'gene_symbol': symbol,
            'A3_baits': ','.join(sorted(info['baits'])),
            'source': ','.join(sorted(info['source'])),
            'R_loop_associated': info['R_loop_associated'],
            'confirmed_coIP': info['confirmed_coIP'],
            'A3B_interactor': 'A3B' in info['baits'],
        })

    out_df = pd.DataFrame(rows)

    # Write full combined list
    out_df.to_csv(OUTPUT_FILE, sep='\t', index=False)
    log(f"  Full list: {OUTPUT_FILE}")
    log(f"  Total genes: {len(out_df)}")

    # Write A3B-only subset
    a3b_file = OUTPUT_FILE.replace('.txt', '_A3B_only.txt')
    a3b_df = out_df[out_df['A3B_interactor'] == True]
    a3b_df.to_csv(a3b_file, sep='\t', index=False)
    log(f"  A3B subset: {a3b_file}")
    log(f"  A3B genes: {len(a3b_df)}")

    # -----------------------------------------------------------------
    # SUMMARY
    # -----------------------------------------------------------------
    log(f"\n{'='*80}")
    log("EXTRACTION COMPLETE")
    log(f"{'='*80}")

    log(f"\nA3B interactor gene list ({len(a3b_df)} genes):")
    for _, row in a3b_df.iterrows():
        flags = []
        if row['R_loop_associated']:
            flags.append('R-loop')
        if row['confirmed_coIP']:
            flags.append('co-IP')
        if row['source'] == 'Jang_2024,McCann_2023':
            flags.append('BOTH')
        flag_str = f"  [{', '.join(flags)}]" if flags else ""
        log(f"  {row['gene_symbol']:20s} source={row['source']:30s}{flag_str}")

    log(f"\nOutput files:")
    log(f"  1. {OUTPUT_FILE}")
    log(f"     All A3 family interactors ({len(out_df)} genes)")
    log(f"  2. {a3b_file}")
    log(f"     A3B-specific interactors ({len(a3b_df)} genes)")
    log(f"\n  McCann 2023 list: verified from Supplementary Table 1, Layer 1")
    log(f"  Jang 2024 list: automated extraction from mmc15.xlsx (BFDR<0.05, wd>=0.90)")


if __name__ == "__main__":
    main()
