#!/usr/bin/env python3
"""
run-config command
==================

Execute the ClusterCatcher Snakemake pipeline using a configuration file
generated by the create-config command.
"""

import click
import os
import sys
import yaml
import subprocess
from pathlib import Path


def find_snakefile():
    """
    Find the Snakefile location within the installed package.
    
    Returns
    -------
    str
        Path to Snakefile
    """
    # Check relative to this file (development mode)
    cli_dir = Path(__file__).parent
    dev_snakefile = cli_dir.parent / 'snakemake_wrapper' / 'Snakefile'
    if dev_snakefile.exists():
        return str(dev_snakefile)
    
    # Check in installed package location
    try:
        import ClusterCatcher
        pkg_dir = Path(ClusterCatcher.__file__).parent
        installed_snakefile = pkg_dir / 'snakemake_wrapper' / 'Snakefile'
        if installed_snakefile.exists():
            return str(installed_snakefile)
    except ImportError:
        pass
    
    # Try site-packages
    try:
        import site
        for sp in site.getsitepackages():
            sp_snakefile = Path(sp) / 'ClusterCatcher' / 'snakemake_wrapper' / 'Snakefile'
            if sp_snakefile.exists():
                return str(sp_snakefile)
    except Exception:
        pass
    
    # Try current directory
    cwd_snakefile = Path.cwd() / 'snakemake_wrapper' / 'Snakefile'
    if cwd_snakefile.exists():
        return str(cwd_snakefile)
    
    # Try parent directory (if running from snakemake_wrapper)
    parent_snakefile = Path.cwd() / 'Snakefile'
    if parent_snakefile.exists():
        return str(parent_snakefile)
    
    return None


def validate_config_file(config_path):
    """
    Load and validate configuration file.
    
    Parameters
    ----------
    config_path : str
        Path to configuration YAML
        
    Returns
    -------
    tuple
        (config_dict, errors)
    """
    errors = []
    
    try:
        with open(config_path, 'r') as f:
            config = yaml.safe_load(f)
    except Exception as e:
        return None, [f"Failed to load config: {e}"]
    
    # Basic validation
    if config is None:
        return None, ["Config file is empty"]
    
    # Check for samples - can be either 'samples' dict or 'sample_info' pickle path
    has_samples = 'samples' in config and config['samples']
    has_sample_info = 'sample_info' in config and config['sample_info']
    has_sample_ids = 'sample_ids' in config and config['sample_ids']
    
    if not (has_samples or has_sample_info or has_sample_ids):
        errors.append("Missing sample information: need 'samples', 'sample_info', or 'sample_ids'")
    
    # Check output_dir
    if 'output_dir' not in config:
        errors.append("Missing required key: output_dir")
    
    # Check reference
    if 'reference' not in config:
        errors.append("Missing required key: reference")
    elif config['reference']:
        if not config['reference'].get('cellranger'):
            errors.append("Missing reference.cellranger (Cell Ranger reference path)")
    
    # Check annotation config (popV)
    if 'annotation' in config and config['annotation']:
        annotation = config['annotation']
        # Check for popV config (new structure)
        if 'popv_huggingface_repo' not in annotation:
            # Could be using old config format - warn but don't error
            if 'method' in annotation:
                errors.append("Old annotation config format detected. Please regenerate config with create_config.py")
    
    # Check QC config
    if 'qc' in config and config['qc']:
        qc = config['qc']
        # Ensure all required QC params are present
        required_qc = ['min_genes', 'max_mito_pct', 'doublet_rate']
        for param in required_qc:
            if param not in qc:
                errors.append(f"Missing qc.{param}")
    
    # Check preprocessing config
    if 'preprocessing' not in config:
        errors.append("Missing preprocessing config section")
    
    return config, errors


def get_expected_outputs(config):
    """
    Get list of expected output files based on config.
    
    Parameters
    ----------
    config : dict
        Pipeline configuration
        
    Returns
    -------
    list
        List of (filepath, description) tuples
    """
    outputs = []
    modules = config.get('modules', {})
    
    # Always generated
    outputs.append(('qc/qc_metrics.tsv', 'QC metrics'))
    outputs.append(('qc/multiqc_report.html', 'MultiQC report'))
    outputs.append(('annotation/adata_annotated.h5ad', 'Annotated AnnData'))
    outputs.append(('annotation/annotation_summary.tsv', 'Annotation summary'))
    outputs.append(('figures/qc/', 'QC and annotation figures'))
    
    # Dysregulation (default enabled)
    if modules.get('dysregulation', True):
        outputs.append(('dysregulation/adata_cancer_detected.h5ad', 'Cancer detection AnnData'))
        outputs.append(('dysregulation/dysregulation_summary.tsv', 'Dysregulation summary'))
    
    # Viral detection
    if modules.get('viral', False):
        outputs.append(('viral/viral_detection_summary.tsv', 'Viral detection summary'))
        outputs.append(('viral/viral_counts.h5ad', 'Viral counts AnnData'))
        if config.get('viral', {}).get('viral_db'):
            outputs.append(('viral_integration/adata_with_virus.h5ad', 'Viral integration AnnData'))
    
    # SComatic
    if modules.get('scomatic', False):
        outputs.append(('mutations/all_samples.single_cell_genotype.filtered.tsv', 'Filtered mutations'))
        outputs.append(('mutations/CombinedCallableSites/complete_callable_sites.tsv', 'Callable sites'))
    
    # Signatures
    if modules.get('signatures', False):
        outputs.append(('signatures/signature_weights_per_cell.txt', 'Signature weights'))
        outputs.append(('signatures/adata_final.h5ad', 'Final AnnData with signatures'))
        outputs.append(('adata_final.h5ad', 'Final AnnData (copy)'))
    
    # Always generated
    outputs.append(('master_summary.yaml', 'Pipeline summary'))
    
    return outputs


@click.command('run-config')
@click.argument('config_yaml', type=click.Path(exists=True))
@click.option(
    '--cores', '-c',
    default=8,
    type=int,
    help='Total number of cores for Snakemake (default: 8)'
)
@click.option(
    '--jobs', '-j',
    default=1,
    type=int,
    help='Number of concurrent jobs (default: 1)'
)
@click.option(
    '--dryrun', '-n',
    is_flag=True,
    default=False,
    help='Perform a dry run (show what would be done)'
)
@click.option(
    '--unlock',
    is_flag=True,
    default=False,
    help='Unlock working directory (if previous run was interrupted)'
)
@click.option(
    '--rerun-incomplete',
    is_flag=True,
    default=False,
    help='Rerun incomplete jobs'
)
@click.option(
    '--keep-going', '-k',
    is_flag=True,
    default=False,
    help='Keep going with independent jobs after error'
)
@click.option(
    '--use-conda/--no-conda',
    default=True,
    help='Use conda environments for rules (default: True)'
)
@click.option(
    '--conda-frontend',
    default='mamba',
    type=click.Choice(['mamba', 'conda']),
    help='Conda frontend to use (default: mamba)'
)
@click.option(
    '--profile',
    type=click.Path(),
    help='Path to Snakemake profile for cluster execution'
)
@click.option(
    '--cluster',
    type=str,
    help='Cluster submission command (e.g., "sbatch --partition=normal")'
)
@click.option(
    '--cluster-config',
    type=click.Path(),
    help='Path to cluster configuration file'
)
@click.option(
    '--latency-wait',
    default=60,
    type=int,
    help='Wait time for filesystem latency in seconds (default: 60)'
)
@click.option(
    '--targets',
    type=str,
    help='Comma-separated list of specific targets to build'
)
@click.option(
    '--until',
    type=str,
    help='Run pipeline until specified rule'
)
@click.option(
    '--forcerun',
    type=str,
    help='Force rerun of specific rules (comma-separated)'
)
@click.option(
    '--verbose', '-v',
    is_flag=True,
    default=False,
    help='Verbose Snakemake output'
)
@click.option(
    '--quiet', '-q',
    is_flag=True,
    default=False,
    help='Quiet Snakemake output'
)
@click.option(
    '--snakefile', '-s',
    type=click.Path(),
    help='Path to Snakefile (auto-detected if not provided)'
)
def run_config(config_yaml, cores, jobs, dryrun, unlock, rerun_incomplete,
               keep_going, use_conda, conda_frontend, profile, cluster,
               cluster_config, latency_wait, targets, until, forcerun,
               verbose, quiet, snakefile):
    """
    Run the ClusterCatcher pipeline from a config file.
    
    This command executes the full Snakemake pipeline using the configuration
    generated by create-config. It supports local execution, cluster submission,
    and various Snakemake options for debugging and optimization.
    
    \b
    Local execution:
      ClusterCatcher run-config config.yaml --cores 16
    
    \b
    Cluster execution (SLURM example):
      ClusterCatcher run-config config.yaml \\
        --cores 100 \\
        --jobs 10 \\
        --cluster "sbatch --partition=normal --nodes=1 --ntasks-per-node={threads} --time=04:00:00"
    
    \b
    Using a Snakemake profile:
      ClusterCatcher run-config config.yaml --profile /path/to/profile
    
    \b
    Dry run to check pipeline:
      ClusterCatcher run-config config.yaml --dryrun
    
    \b
    Run specific rules:
      ClusterCatcher run-config config.yaml --until qc_and_annotation
    """
    
    click.echo(f"\n{'='*60}")
    click.echo("ClusterCatcher: run-config")
    click.echo(f"{'='*60}\n")
    
    # Find Snakefile
    if snakefile:
        if not os.path.exists(snakefile):
            click.echo(f"ERROR: Snakefile not found: {snakefile}", err=True)
            sys.exit(1)
    else:
        snakefile = find_snakefile()
        if snakefile is None:
            click.echo("ERROR: Could not find Snakefile", err=True)
            click.echo("Please provide --snakefile or ensure ClusterCatcher is properly installed", err=True)
            click.echo("\nTry one of these:", err=True)
            click.echo("  1. Run from the ClusterCatcher directory", err=True)
            click.echo("  2. Provide --snakefile /path/to/Snakefile", err=True)
            sys.exit(1)
    
    click.echo(f"Snakefile: {snakefile}")
    
    # Validate config
    click.echo(f"Config: {config_yaml}")
    config, errors = validate_config_file(config_yaml)
    if errors:
        click.echo("ERROR: Configuration validation failed:", err=True)
        for e in errors:
            click.echo(f"  - {e}", err=True)
        sys.exit(1)
    
    # Display config summary
    n_samples = 0
    if 'samples' in config and config['samples']:
        n_samples = len(config['samples'])
    elif 'sample_ids' in config and config['sample_ids']:
        n_samples = len(config['sample_ids'])
    
    click.echo(f"Samples: {n_samples}")
    click.echo(f"Output directory: {config.get('output_dir', 'N/A')}")
    
    # Show enabled modules
    modules = config.get('modules', {})
    enabled = [k for k, v in modules.items() if v]
    if enabled:
        click.echo(f"Enabled modules: {', '.join(enabled)}")
    
    # Show annotation config
    annotation = config.get('annotation', {})
    if annotation.get('popv_huggingface_repo'):
        click.echo(f"Annotation: popV ({annotation['popv_huggingface_repo']})")
    
    # Build Snakemake command
    cmd = ['snakemake']
    
    # Core options
    cmd.extend(['--snakefile', snakefile])
    cmd.extend(['--configfile', os.path.abspath(config_yaml)])
    cmd.extend(['--cores', str(cores)])
    cmd.extend(['--jobs', str(jobs)])
    cmd.extend(['--latency-wait', str(latency_wait)])
    
    # Conda options
    if use_conda:
        cmd.append('--use-conda')
        cmd.extend(['--conda-frontend', conda_frontend])
    
    # Execution modifiers
    if dryrun:
        cmd.append('--dryrun')
    if unlock:
        cmd.append('--unlock')
    if rerun_incomplete:
        cmd.append('--rerun-incomplete')
    if keep_going:
        cmd.append('--keep-going')
    
    # Cluster options
    if profile:
        cmd.extend(['--profile', profile])
    if cluster:
        cmd.extend(['--cluster', cluster])
    if cluster_config:
        cmd.extend(['--cluster-config', cluster_config])
    
    # Target options
    if targets:
        cmd.extend(targets.split(','))
    if until:
        cmd.extend(['--until', until])
    if forcerun:
        for rule in forcerun.split(','):
            cmd.extend(['--forcerun', rule.strip()])
    
    # Verbosity
    if verbose:
        cmd.append('--verbose')
    if quiet:
        cmd.append('--quiet')
    
    # Print command
    click.echo(f"\n{'='*60}")
    click.echo("Snakemake command:")
    click.echo(f"{'='*60}")
    click.echo(' \\\n  '.join(cmd[:6]) + ' \\')
    click.echo('  ' + ' '.join(cmd[6:]))
    click.echo("")
    
    if dryrun:
        click.echo("DRY RUN - showing what would be executed\n")
    else:
        click.echo("Starting pipeline execution...\n")
    
    # Change to snakefile directory for proper relative paths
    original_dir = os.getcwd()
    snakefile_dir = os.path.dirname(snakefile)
    
    # Execute Snakemake
    try:
        result = subprocess.run(cmd, check=False)
        
        if result.returncode == 0:
            click.echo(f"\n{'='*60}")
            click.echo("Pipeline completed successfully!")
            click.echo(f"{'='*60}")
            
            output_dir = config.get('output_dir', 'results')
            click.echo(f"\nResults in: {output_dir}")
            
            # Show expected output files based on config
            expected_outputs = get_expected_outputs(config)
            click.echo("\nExpected output files:")
            for fpath, desc in expected_outputs:
                full_path = os.path.join(output_dir, fpath)
                if os.path.exists(full_path):
                    click.echo(f"  ✓ {fpath}")
                else:
                    # Don't show missing files for disabled modules
                    pass
            
            # Show key files that should always exist
            click.echo("\nKey output files:")
            key_files = [
                ('annotation/adata_annotated.h5ad', 'Annotated cells with popV predictions'),
                ('qc/qc_metrics.tsv', 'Per-sample QC statistics'),
                ('figures/qc/UMAP_final_annotation.pdf', 'Cell type UMAP with labels'),
            ]
            
            # Add module-specific key files
            if modules.get('dysregulation', True):
                key_files.append(('dysregulation/adata_cancer_detected.h5ad', 'Cancer cell detection'))
            if modules.get('scomatic', False):
                key_files.append(('mutations/all_samples.single_cell_genotype.filtered.tsv', 'Somatic mutations'))
            if modules.get('signatures', False):
                key_files.append(('signatures/adata_final.h5ad', 'Final AnnData with signatures'))
            
            key_files.append(('master_summary.yaml', 'Pipeline summary'))
            
            for fpath, desc in key_files:
                full_path = os.path.join(output_dir, fpath)
                if os.path.exists(full_path):
                    click.echo(f"  ✓ {fpath} - {desc}")
                    
        else:
            click.echo(f"\n{'='*60}")
            click.echo(f"Pipeline failed with exit code: {result.returncode}")
            click.echo(f"{'='*60}")
            click.echo("\nTroubleshooting:")
            click.echo("  1. Check the log files in logs/ directory")
            click.echo("  2. Run with --verbose for more details")
            click.echo("  3. Run with --dryrun to check workflow")
            click.echo("  4. Check logs/qc_annotation/qc_annotation.log for annotation errors")
            sys.exit(result.returncode)
            
    except FileNotFoundError:
        click.echo("ERROR: Snakemake not found in PATH", err=True)
        click.echo("Please ensure Snakemake is installed:", err=True)
        click.echo("  conda install -c bioconda snakemake", err=True)
        click.echo("  # or", err=True)
        click.echo("  pip install snakemake", err=True)
        sys.exit(1)
    except KeyboardInterrupt:
        click.echo("\n\nPipeline interrupted by user")
        click.echo("To resume, run the same command again")
        click.echo("To unlock if needed: ClusterCatcher run-config config.yaml --unlock")
        sys.exit(130)
    finally:
        os.chdir(original_dir)


if __name__ == '__main__':
    run_config()
